<?php
declare(strict_types=1);
session_start();

/*
 * News panel — publish, edit and delete articles + photos without external services.
 * Form -> commits markdown + image to GitHub -> GitHub Action redeploys the site (~3 min).
 *
 * Config file `panel-config.php` (generated by CI inside public_html; a manual copy
 * outside the web root takes precedence). See docs/PANEL.md.
 */

// Config search: ancestors of public_html first, webroot last — a file outside
// the web root (e.g. /home/<user>/panel-config.php) always wins over the
// CI-generated one that ships inside public_html.
$dir = __DIR__;
$dirs = [];
for ($i = 0; $i < 6 && $dir !== dirname($dir); $i++) {
    $dirs[] = $dir;
    $dir = dirname($dir);
}
$config = null;
foreach (array_reverse($dirs) as $d) {
    if (is_file($d . '/panel-config.php')) {
        $config = require $d . '/panel-config.php';
        break;
    }
}

const CATEGORIES = ['Campaigns', 'Vatican', 'Mission', 'Community', 'Events', 'General'];
const LOCALES = ['en' => 'English', 'es' => 'Español (Spanish)', 'hi' => 'हिन्दी (Hindi)', 'ml' => 'മലയാളം (Malayalam)'];
const LOCALE_NEWS_BASE = ['en' => '/en/news/', 'es' => '/es/noticias/', 'hi' => '/hi/samachar/', 'ml' => '/ml/varthakal/'];
const MAX_UPLOAD = 12 * 1024 * 1024; // 12 MB

$msg = '';
$err = '';

function e(string $s): string { return htmlspecialchars($s, ENT_QUOTES, 'UTF-8'); }

function slugify(string $t): string {
    $ascii = function_exists('iconv') ? (iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $t) ?: '') : '';
    $s = strtolower(trim(preg_replace('/[^a-zA-Z0-9]+/', '-', $ascii !== '' ? $ascii : $t) ?? '', '-'));
    return $s !== '' ? substr($s, 0, 60) : 'article-' . gmdate('Ymd-Hi');
}

function yamlQuote(string $s): string {
    return "'" . str_replace("'", "''", trim($s)) . "'";
}

function httpRequest(string $method, string $url, array $headers, ?string $body = null): array {
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_CUSTOMREQUEST => $method,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_TIMEOUT => 30,
    ]);
    if ($body !== null) curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
    $resp = curl_exec($ch);
    $code = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
    curl_close($ch);
    return [$code, is_string($resp) ? $resp : ''];
}

function ghHeaders(array $config): array {
    return [
        'Authorization: Bearer ' . $config['github_token'],
        'Accept: application/vnd.github+json',
        'X-GitHub-Api-Version: 2022-11-28',
        'User-Agent: hospitalarias-panel',
        'Content-Type: application/json',
    ];
}

function ghApiUrl(array $config, string $path): string {
    return 'https://api.github.com/repos/' . $config['github_repo'] . '/contents/'
        . implode('/', array_map('rawurlencode', explode('/', $path)));
}

/* Read one repo file. Returns ['content'=>, 'sha'=>] or null. */
function ghGetFile(array $config, string $path): ?array {
    [$code, $body] = httpRequest('GET', ghApiUrl($config, $path) . '?ref=' . rawurlencode($config['github_branch']), ghHeaders($config));
    if ($code !== 200) return null;
    $data = json_decode($body, true);
    if (!is_array($data) || !isset($data['sha'])) return null;
    $raw = isset($data['content']) ? base64_decode(str_replace("\n", '', (string) $data['content'])) : '';
    return ['content' => is_string($raw) ? $raw : '', 'sha' => (string) $data['sha']];
}

/* Commit (or update) one file in the repo. Returns [ok, errorMessage]. */
function ghCommit(array $config, string $path, string $binary, string $message): array {
    $api = ghApiUrl($config, $path);
    $headers = ghHeaders($config);

    $sha = null;
    [$code, $body] = httpRequest('GET', $api . '?ref=' . rawurlencode($config['github_branch']), $headers);
    if ($code === 200) {
        $sha = json_decode($body, true)['sha'] ?? null;
    }

    $payload = [
        'message' => $message,
        'content' => base64_encode($binary),
        'branch' => $config['github_branch'],
    ];
    if ($sha) $payload['sha'] = $sha;

    [$code, $body] = httpRequest('PUT', $api, $headers, json_encode($payload));
    if ($code === 200 || $code === 201) return [true, ''];
    $detail = json_decode($body, true)['message'] ?? $body;
    return [false, "GitHub error {$code} on {$path}: {$detail}"];
}

/* Delete one repo file. Returns [ok, errorMessage]. */
function ghDelete(array $config, string $path, string $message): array {
    $file = ghGetFile($config, $path);
    if (!$file) return [false, "Could not read {$path} on GitHub."];
    [$code, $body] = httpRequest('DELETE', ghApiUrl($config, $path), ghHeaders($config), json_encode([
        'message' => $message,
        'sha' => $file['sha'],
        'branch' => $config['github_branch'],
    ]));
    if ($code === 200) return [true, ''];
    $detail = json_decode($body, true)['message'] ?? $body;
    return [false, "GitHub error {$code} deleting {$path}: {$detail}"];
}

/* List markdown articles for every locale: [['locale','slug','path'], ...] */
function ghListNews(array $config): array {
    $out = [];
    foreach (array_keys(LOCALES) as $loc) {
        [$code, $body] = httpRequest('GET', ghApiUrl($config, "src/content/news/{$loc}") . '?ref=' . rawurlencode($config['github_branch']), ghHeaders($config));
        if ($code !== 200) continue;
        foreach ((json_decode($body, true) ?: []) as $item) {
            if (($item['type'] ?? '') === 'file' && str_ends_with((string) $item['name'], '.md')) {
                $out[] = ['locale' => $loc, 'slug' => substr($item['name'], 0, -3), 'path' => (string) $item['path']];
            }
        }
    }
    return $out;
}

/* Split a news markdown file into frontmatter fields + body. */
function parseNewsFile(string $md): array {
    $fields = ['title' => '', 'date' => '', 'category' => 'General', 'image' => '', 'imageAlt' => '', 'description' => ''];
    $body = $md;
    if (preg_match('/^---\R(.*?)\R---\R?(.*)$/s', $md, $m)) {
        $body = trim($m[2]);
        foreach (preg_split('/\R/', $m[1]) ?: [] as $line) {
            if (!preg_match('/^(\w+):\s*(.*)$/', $line, $kv)) continue;
            [$k, $v] = [$kv[1], trim($kv[2])];
            if (strlen($v) >= 2 && $v[0] === "'" && str_ends_with($v, "'")) {
                $v = str_replace("''", "'", substr($v, 1, -1));
            } elseif (strlen($v) >= 2 && $v[0] === '"' && str_ends_with($v, '"')) {
                $v = str_replace('\\"', '"', substr($v, 1, -1));
            }
            if (array_key_exists($k, $fields)) $fields[$k] = $v;
        }
    }
    $fields['date'] = substr($fields['date'], 0, 10);
    return [$fields, $body];
}

/* Returns [binary, extension] or null on unsupported type. */
function processImage(string $tmpPath, string $mime): ?array {
    $extMap = ['image/jpeg' => 'jpg', 'image/png' => 'png', 'image/webp' => 'webp'];
    if (!isset($extMap[$mime])) return null;

    if (function_exists('imagecreatefromstring')) {
        $img = @imagecreatefromstring((string) file_get_contents($tmpPath));
        if ($img !== false) {
            if (imagesx($img) > 1600) {
                $resized = imagescale($img, 1600);
                if ($resized !== false) { imagedestroy($img); $img = $resized; }
            }
            ob_start();
            imagejpeg($img, null, 82);
            $bin = (string) ob_get_clean();
            imagedestroy($img);
            return [$bin, 'jpg'];
        }
    }
    return [(string) file_get_contents($tmpPath), $extMap[$mime]];
}

// ---------- Auth ----------
if (isset($_GET['logout'])) {
    session_destroy();
    header('Location: panel.php');
    exit;
}

if (isset($_POST['action']) && $_POST['action'] === 'login') {
    if ($config && hash_equals((string) $config['panel_password'], (string) ($_POST['password'] ?? ''))) {
        session_regenerate_id(true);
        $_SESSION['ok'] = true;
        $_SESSION['csrf'] = bin2hex(random_bytes(16));
    } else {
        sleep(1);
        $err = 'Incorrect password.';
    }
}

$logged = !empty($_SESSION['ok']);

$csrfOk = function (): bool {
    return hash_equals((string) ($_SESSION['csrf'] ?? ''), (string) ($_POST['csrf'] ?? ''));
};

// ---------- Edit: load an existing article (?edit=<locale>/<slug>) ----------
$editing = null;
if ($logged && $config && isset($_GET['edit'])) {
    if (preg_match('#^(en|es|hi|ml)/([a-z0-9-]+)$#', (string) $_GET['edit'], $m)) {
        $file = ghGetFile($config, "src/content/news/{$m[1]}/{$m[2]}.md");
        if ($file) {
            [$fields, $body] = parseNewsFile($file['content']);
            $editing = ['locale' => $m[1], 'slug' => $m[2], 'fields' => $fields, 'body' => $body];
        } else {
            $err = 'Could not load that article from GitHub.';
        }
    }
}

// ---------- Delete ----------
if ($logged && isset($_POST['action']) && $_POST['action'] === 'delete') {
    if (!$csrfOk()) {
        $err = 'Session expired — please try again.';
    } elseif (!$config) {
        $err = 'Panel is not configured yet.';
    } else {
        $path = (string) ($_POST['path'] ?? '');
        if (!preg_match('#^src/content/news/(en|es|hi|ml)/[a-z0-9-]+\.md$#', $path)) {
            $err = 'Invalid article path.';
        } else {
            // If the article uses a panel-managed photo, remove it too (best effort).
            $file = ghGetFile($config, $path);
            $imgPath = null;
            if ($file) {
                [$fields] = parseNewsFile($file['content']);
                if (preg_match('#^/images/news/[a-z0-9-]+\.(jpg|png|webp)$#', $fields['image'])) {
                    $imgPath = 'public' . $fields['image'];
                }
            }
            [$ok, $delErr] = ghDelete($config, $path, "news: delete {$path}");
            if (!$ok) {
                $err = $delErr;
            } else {
                if ($imgPath) ghDelete($config, $imgPath, "news: delete photo for {$path}");
                $msg = "Deleted \"{$path}\". The site will update in about 3-5 minutes.";
            }
        }
    }
    $_SESSION['csrf'] = bin2hex(random_bytes(16));
}

// ---------- Publish / Update ----------
if ($logged && isset($_POST['action']) && $_POST['action'] === 'publish') {
    if (!$csrfOk()) {
        $err = 'Session expired — please try again.';
    } elseif (!$config) {
        $err = 'Panel is not configured yet. Ask Luis to create panel-config.php (see docs/PANEL.md).';
    } else {
        // Edit mode: keep the original slug + locale so the same file is updated.
        $editSlug = (string) ($_POST['edit_slug'] ?? '');
        $editLocale = (string) ($_POST['edit_locale'] ?? '');
        $isEdit = $editSlug !== '' && preg_match('/^[a-z0-9-]+$/', $editSlug) && isset(LOCALES[$editLocale]);
        $origImage = (string) ($_POST['orig_image'] ?? '');
        if (!preg_match('#^/images/[a-zA-Z0-9_/.-]+$#', $origImage)) $origImage = '';

        $locale = $isEdit ? $editLocale : (string) ($_POST['locale'] ?? 'en');
        $title = trim((string) ($_POST['title'] ?? ''));
        $category = in_array($_POST['category'] ?? '', CATEGORIES, true) ? (string) $_POST['category'] : 'General';
        $description = trim((string) ($_POST['description'] ?? ''));
        $imageAlt = trim((string) ($_POST['image_alt'] ?? ''));
        $body = trim((string) ($_POST['body'] ?? ''));
        $date = preg_match('/^\d{4}-\d{2}-\d{2}$/', (string) ($_POST['date'] ?? ''))
            ? (string) $_POST['date'] : gmdate('Y-m-d');

        $hasPhoto = !empty($_FILES['photo']) && $_FILES['photo']['error'] === UPLOAD_ERR_OK;
        $photoMissing = !$hasPhoto && (!$isEdit || $origImage === '');

        if (!isset(LOCALES[$locale])) $err = 'Please choose a valid language.';
        elseif ($title === '' || $body === '' || $description === '' || $imageAlt === '') {
            $err = 'Please fill in every field.';
        } elseif ($hasPhoto && $_FILES['photo']['size'] > MAX_UPLOAD) {
            $err = 'The photo is too large (max 12 MB).';
        } elseif ($photoMissing) {
            $err = 'Please attach a photo (JPG, PNG or WebP, up to 12 MB).';
        } else {
            $slug = $isEdit ? $editSlug : slugify($title);
            $imgWebPath = $origImage;
            $imgRepoPath = null;
            $imgBin = null;

            if ($hasPhoto) {
                $mime = (string) (new finfo(FILEINFO_MIME_TYPE))->file($_FILES['photo']['tmp_name']);
                $image = processImage($_FILES['photo']['tmp_name'], $mime);
                if (!$image) {
                    $err = 'The photo must be a JPG, PNG or WebP image.';
                } else {
                    [$imgBin, $ext] = $image;
                    $imgRepoPath = "public/images/news/{$slug}.{$ext}";
                    $imgWebPath = "/images/news/{$slug}.{$ext}";
                }
            }

            if ($err === '') {
                $md = "---\n"
                    . 'title: ' . yamlQuote($title) . "\n"
                    . "date: {$date}T00:00:00.000Z\n"
                    . "category: {$category}\n"
                    . "image: {$imgWebPath}\n"
                    . 'imageAlt: ' . yamlQuote($imageAlt) . "\n"
                    . 'description: ' . yamlQuote($description) . "\n"
                    . "---\n\n" . $body . "\n";

                if ($imgRepoPath) {
                    [$okImg, $errImg] = ghCommit($config, $imgRepoPath, (string) $imgBin, "news: photo for {$slug}");
                    if (!$okImg) $err = $errImg;
                }
                if ($err === '') {
                    [$okMd, $errMd] = ghCommit($config, "src/content/news/{$locale}/{$slug}.md", $md, ($isEdit ? 'news: update ' : 'news: ') . $title);
                    if ($okMd) {
                        $base = LOCALE_NEWS_BASE[$locale];
                        $verb = $isEdit ? 'Updated' : 'Published';
                        $msg = "{$verb} \"{$title}\". It will appear at https://hospitalarias.in{$base} in about 3-5 minutes.";
                    } else {
                        $err = $errMd;
                    }
                }
            }
        }
    }
    $_SESSION['csrf'] = bin2hex(random_bytes(16)); // rotate token
}

// ---------- Manage list ----------
$articles = ($logged && $config) ? ghListNews($config) : [];
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>News Panel — Benedict Menni Centre</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; background: #f4f2ef; color: #26221e; margin: 0; padding: 24px; }
  .card { max-width: 560px; margin: 0 auto 24px; background: #fff; border-radius: 14px; padding: 28px; box-shadow: 0 6px 24px rgba(0,0,0,.08); }
  h1 { font-size: 1.35rem; margin: 0 0 4px; }
  h2 { font-size: 1.1rem; margin: 0 0 12px; }
  .sub { color: #6b655c; font-size: .9rem; margin: 0 0 20px; }
  label { display: block; font-weight: 600; font-size: .85rem; margin: 16px 0 4px; }
  input, select, textarea { width: 100%; padding: 11px 12px; border: 1px solid #d8d2c8; border-radius: 8px; font: inherit; font-size: 1rem; background: #fff; }
  input[readonly] { background: #f4f2ef; }
  textarea { min-height: 160px; resize: vertical; }
  .hint { font-size: .78rem; color: #6b655c; margin-top: 3px; }
  button { margin-top: 22px; width: 100%; padding: 13px; border: 0; border-radius: 8px; background: #7a2e2e; color: #fff; font-size: 1rem; font-weight: 700; cursor: pointer; }
  button:hover { background: #612525; }
  .ok { background: #e8f5e9; border: 1px solid #a5d6a7; color: #1b5e20; padding: 12px 14px; border-radius: 8px; margin-bottom: 16px; }
  .err { background: #fdecea; border: 1px solid #f5b7b1; color: #922; padding: 12px 14px; border-radius: 8px; margin-bottom: 16px; }
  .row { display: flex; gap: 12px; } .row > div { flex: 1; }
  .links { display: flex; justify-content: space-between; margin-top: 18px; font-size: .85rem; }
  a { color: #7a2e2e; }
  .articles { width: 100%; border-collapse: collapse; font-size: .85rem; }
  .articles th { text-align: left; color: #6b655c; font-size: .75rem; text-transform: uppercase; letter-spacing: .04em; padding: 6px 6px 6px 0; border-bottom: 1px solid #e6e0d8; }
  .articles td { padding: 7px 6px 7px 0; border-bottom: 1px solid #f0ece5; vertical-align: middle; }
  .badge { display: inline-block; background: #f0ece5; border-radius: 6px; padding: 1px 7px; font-size: .72rem; font-weight: 700; text-transform: uppercase; }
  .art-actions { white-space: nowrap; text-align: right; }
  .art-actions a, .art-actions button { margin: 0; width: auto; display: inline-block; padding: 5px 10px; font-size: .8rem; border-radius: 6px; }
  .btn-edit { background: #f0ece5; color: #26221e; text-decoration: none; }
  .btn-del { background: #fdecea; color: #922; border: 1px solid #f5b7b1; }
  form.inline { display: inline; margin: 0; }
  .empty { color: #6b655c; font-size: .9rem; }
</style>
</head>
<body>

<?php if ($logged): ?>
<div class="card">
  <h2>Manage articles</h2>
  <?php if ($articles): ?>
    <table class="articles">
      <tr><th>Lang</th><th>Article</th><th></th></tr>
      <?php foreach ($articles as $a): ?>
        <tr>
          <td><span class="badge"><?= e($a['locale']) ?></span></td>
          <td>
            <?= e($a['slug']) ?><br>
            <a href="https://hospitalarias.in<?= e(LOCALE_NEWS_BASE[$a['locale']]) . e($a['slug']) ?>/" target="_blank" rel="noopener" style="font-size:.78rem">View ↗</a>
          </td>
          <td class="art-actions">
            <a class="btn-edit" href="?edit=<?= e($a['locale'] . '/' . $a['slug']) ?>">Edit</a>
            <form class="inline" method="post" onsubmit="return confirm('Delete &quot;<?= e($a['slug']) ?>&quot;? This cannot be undone.');">
              <input type="hidden" name="action" value="delete">
              <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">
              <input type="hidden" name="path" value="<?= e($a['path']) ?>">
              <button type="submit" class="btn-del">Delete</button>
            </form>
          </td>
        </tr>
      <?php endforeach; ?>
    </table>
  <?php else: ?>
    <p class="empty">No articles found on GitHub.</p>
  <?php endif; ?>
</div>
<?php endif; ?>

<div class="card">
  <h1><?= $editing ? 'Edit article' : 'News Panel' ?></h1>
  <p class="sub">Benedict Menni Psychosocial Rehabilitation Centre</p>

  <?php if ($msg): ?><div class="ok"><?= e($msg) ?></div><?php endif; ?>
  <?php if ($err): ?><div class="err"><?= e($err) ?></div><?php endif; ?>

  <?php if (!$logged): ?>
    <form method="post">
      <input type="hidden" name="action" value="login">
      <label for="password">Password</label>
      <input type="password" id="password" name="password" required autofocus autocomplete="current-password">
      <button type="submit">Sign in</button>
    </form>
  <?php else: ?>
    <form method="post" enctype="multipart/form-data">
      <input type="hidden" name="action" value="publish">
      <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">
      <?php if ($editing): ?>
        <input type="hidden" name="edit_slug" value="<?= e($editing['slug']) ?>">
        <input type="hidden" name="edit_locale" value="<?= e($editing['locale']) ?>">
        <input type="hidden" name="orig_image" value="<?= e($editing['fields']['image']) ?>">
      <?php endif; ?>

      <div class="row">
        <div>
          <label for="locale">Article language</label>
          <?php if ($editing): ?>
            <input type="text" value="<?= e(LOCALES[$editing['locale']]) ?>" readonly>
          <?php else: ?>
            <select id="locale" name="locale">
              <?php foreach (LOCALES as $code => $label): ?>
                <option value="<?= e($code) ?>"><?= e($label) ?></option>
              <?php endforeach; ?>
            </select>
          <?php endif; ?>
        </div>
        <div>
          <label for="date">Date</label>
          <input type="date" id="date" name="date" value="<?= e($editing ? $editing['fields']['date'] : gmdate('Y-m-d')) ?>">
        </div>
      </div>

      <label for="title">Title</label>
      <input type="text" id="title" name="title" required maxlength="140" value="<?= e($editing ? $editing['fields']['title'] : '') ?>">
      <?php if ($editing): ?><p class="hint">Editing <strong><?= e($editing['slug']) ?>.md</strong> — the URL stays the same.</p><?php endif; ?>

      <label for="category">Category</label>
      <select id="category" name="category">
        <?php
        $cats = CATEGORIES;
        $cur = $editing ? $editing['fields']['category'] : '';
        if ($cur !== '' && !in_array($cur, $cats, true)) array_unshift($cats, $cur);
        foreach ($cats as $c): ?>
          <option <?= $c === $cur ? 'selected' : '' ?>><?= e($c) ?></option>
        <?php endforeach; ?>
      </select>

      <label for="description">Short description</label>
      <input type="text" id="description" name="description" required maxlength="200" value="<?= e($editing ? $editing['fields']['description'] : '') ?>">
      <p class="hint">One or two sentences — shown on the news card.</p>

      <label for="photo">Photo</label>
      <input type="file" id="photo" name="photo" accept="image/jpeg,image/png,image/webp" <?= $editing ? '' : 'required' ?>>
      <p class="hint"><?= $editing ? 'Leave empty to keep the current photo.' : 'JPG, PNG or WebP, up to 12 MB. Large photos are resized automatically.' ?></p>
      <?php if ($editing && $editing['fields']['image'] !== ''): ?>
        <p class="hint">Current: <a href="https://hospitalarias.in<?= e($editing['fields']['image']) ?>" target="_blank" rel="noopener"><?= e($editing['fields']['image']) ?></a></p>
      <?php endif; ?>

      <label for="image_alt">Photo description</label>
      <input type="text" id="image_alt" name="image_alt" required maxlength="160" value="<?= e($editing ? $editing['fields']['imageAlt'] : '') ?>">
      <p class="hint">Describe the photo for blind readers, e.g. "Residents at the garden workshop".</p>

      <label for="body">Article text</label>
      <textarea id="body" name="body" required><?= e($editing ? $editing['body'] : '') ?></textarea>
      <p class="hint">Plain text. Leave an empty line between paragraphs.</p>

      <button type="submit"><?= $editing ? 'Update article' : 'Publish' ?></button>
    </form>
    <div class="links">
      <?php if ($editing): ?><a href="panel.php">+ New article</a><?php endif; ?>
      <a href="https://hospitalarias.in/en/news/" target="_blank" rel="noopener">View news page ↗</a>
      <a href="?logout=1">Sign out</a>
    </div>
  <?php endif; ?>
</div>
</body>
</html>
