<?php
declare(strict_types=1);
// Long-lived session: writing an article can take a while.
session_set_cookie_params([
    'lifetime' => 8 * 3600,
    'path' => '/',
    'secure' => !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off',
    'httponly' => true,
    'samesite' => 'Lax',
]);
ini_set('session.gc_maxlifetime', (string) (8 * 3600));
session_start();

/*
 * News panel — publish, edit and delete articles + photos without external services.
 * Form -> commits markdown + image to GitHub -> GitHub Action redeploys the site (~3 min).
 *
 * Config file `panel-config.php` (generated by CI inside public_html; a manual copy
 * outside the web root takes precedence). See docs/PANEL.md.
 */

// Config search: ancestors of public_html first, webroot last — a file outside
// the web root (e.g. /home/<user>/panel-config.php) always wins over the
// CI-generated one that ships inside public_html.
$dir = __DIR__;
$dirs = [];
for ($i = 0; $i < 6 && $dir !== dirname($dir); $i++) {
    $dirs[] = $dir;
    $dir = dirname($dir);
}
$config = null;
foreach (array_reverse($dirs) as $d) {
    if (is_file($d . '/panel-config.php')) {
        $config = require $d . '/panel-config.php';
        break;
    }
}

const CATEGORIES = ['Campaigns', 'Vatican', 'Mission', 'Community', 'Events', 'General'];
const LOCALES = ['en' => 'English', 'es' => 'Español (Spanish)', 'hi' => 'हिन्दी (Hindi)', 'ml' => 'മലയാളം (Malayalam)'];
const LOCALE_NEWS_BASE = ['en' => '/en/news/', 'es' => '/es/noticias/', 'hi' => '/hi/samachar/', 'ml' => '/ml/varthakal/'];
const MAX_UPLOAD = 12 * 1024 * 1024; // 12 MB photos
const MAX_VIDEO_UPLOAD = 45 * 1024 * 1024; // 45 MB videos — bigger belongs on YouTube

$msg = '';
$err = '';

function e(string $s): string { return htmlspecialchars($s, ENT_QUOTES, 'UTF-8'); }

function slugify(string $t): string {
    $ascii = function_exists('iconv') ? (iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $t) ?: '') : '';
    $s = strtolower(trim(preg_replace('/[^a-zA-Z0-9]+/', '-', $ascii !== '' ? $ascii : $t) ?? '', '-'));
    return $s !== '' ? substr($s, 0, 60) : 'article-' . gmdate('Ymd-Hi');
}

function yamlQuote(string $s): string {
    return "'" . str_replace("'", "''", trim($s)) . "'";
}

function httpRequest(string $method, string $url, array $headers, ?string $body = null, int $timeout = 30): array {
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_CUSTOMREQUEST => $method,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_TIMEOUT => $timeout,
    ]);
    if ($body !== null) curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
    $resp = curl_exec($ch);
    $code = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
    curl_close($ch);
    return [$code, is_string($resp) ? $resp : ''];
}

function ghHeaders(array $config): array {
    return [
        'Authorization: Bearer ' . $config['github_token'],
        'Accept: application/vnd.github+json',
        'X-GitHub-Api-Version: 2022-11-28',
        'User-Agent: hospitalarias-panel',
        'Content-Type: application/json',
    ];
}

function ghApiUrl(array $config, string $path): string {
    return 'https://api.github.com/repos/' . $config['github_repo'] . '/contents/'
        . implode('/', array_map('rawurlencode', explode('/', $path)));
}

/* Read one repo file. Returns ['content'=>, 'sha'=>] or null. */
function ghGetFile(array $config, string $path): ?array {
    [$code, $body] = httpRequest('GET', ghApiUrl($config, $path) . '?ref=' . rawurlencode($config['github_branch']), ghHeaders($config));
    if ($code !== 200) return null;
    $data = json_decode($body, true);
    if (!is_array($data) || !isset($data['sha'])) return null;
    $raw = isset($data['content']) ? base64_decode(str_replace("\n", '', (string) $data['content'])) : '';
    return ['content' => is_string($raw) ? $raw : '', 'sha' => (string) $data['sha']];
}

/* Commit (or update) one file in the repo. Returns [ok, errorMessage]. */
function ghCommit(array $config, string $path, string $binary, string $message): array {
    $api = ghApiUrl($config, $path);
    $headers = ghHeaders($config);

    $sha = null;
    [$code, $body] = httpRequest('GET', $api . '?ref=' . rawurlencode($config['github_branch']), $headers);
    if ($code === 200) {
        $sha = json_decode($body, true)['sha'] ?? null;
    }

    $payload = [
        'message' => $message,
        'content' => base64_encode($binary),
        'branch' => $config['github_branch'],
    ];
    if ($sha) $payload['sha'] = $sha;

    // Videos push a big base64 payload — give the PUT more time.
    [$code, $body] = httpRequest('PUT', $api, $headers, json_encode($payload), strlen($binary) > 4 * 1024 * 1024 ? 120 : 30);
    if ($code === 200 || $code === 201) return [true, ''];
    $detail = json_decode($body, true)['message'] ?? $body;
    return [false, "GitHub error {$code} on {$path}: {$detail}"];
}

/* Delete one repo file. Returns [ok, errorMessage]. */
function ghDelete(array $config, string $path, string $message): array {
    $file = ghGetFile($config, $path);
    if (!$file) return [false, "Could not read {$path} on GitHub."];
    [$code, $body] = httpRequest('DELETE', ghApiUrl($config, $path), ghHeaders($config), json_encode([
        'message' => $message,
        'sha' => $file['sha'],
        'branch' => $config['github_branch'],
    ]));
    if ($code === 200) return [true, ''];
    $detail = json_decode($body, true)['message'] ?? $body;
    return [false, "GitHub error {$code} deleting {$path}: {$detail}"];
}

/* List markdown articles for every locale: [['locale','slug','path'], ...] */
function ghListNews(array $config): array {
    $out = [];
    foreach (array_keys(LOCALES) as $loc) {
        [$code, $body] = httpRequest('GET', ghApiUrl($config, "src/content/news/{$loc}") . '?ref=' . rawurlencode($config['github_branch']), ghHeaders($config));
        if ($code !== 200) continue;
        foreach ((json_decode($body, true) ?: []) as $item) {
            if (($item['type'] ?? '') === 'file' && str_ends_with((string) $item['name'], '.md')) {
                $out[] = ['locale' => $loc, 'slug' => substr($item['name'], 0, -3), 'path' => (string) $item['path']];
            }
        }
    }
    return $out;
}

/* Split a news markdown file into frontmatter fields + body. */
function parseNewsFile(string $md): array {
    $fields = ['title' => '', 'date' => '', 'category' => 'General', 'image' => '', 'imageAlt' => '', 'description' => '', 'video' => ''];
    $body = $md;
    if (preg_match('/^---\R(.*?)\R---\R?(.*)$/s', $md, $m)) {
        $body = trim($m[2]);
        foreach (preg_split('/\R/', $m[1]) ?: [] as $line) {
            if (!preg_match('/^(\w+):\s*(.*)$/', $line, $kv)) continue;
            [$k, $v] = [$kv[1], trim($kv[2])];
            if (strlen($v) >= 2 && $v[0] === "'" && str_ends_with($v, "'")) {
                $v = str_replace("''", "'", substr($v, 1, -1));
            } elseif (strlen($v) >= 2 && $v[0] === '"' && str_ends_with($v, '"')) {
                $v = str_replace('\\"', '"', substr($v, 1, -1));
            }
            if (array_key_exists($k, $fields)) $fields[$k] = $v;
        }
    }
    $fields['date'] = substr($fields['date'], 0, 10);
    return [$fields, $body];
}

/* Returns [binary, extension] or null on unsupported type. Videos are stored
   as-is — no transcoding on shared hosting. */
function processVideo(string $tmpPath, string $mime): ?array {
    $extMap = ['video/mp4' => 'mp4', 'video/webm' => 'webm', 'video/quicktime' => 'mov'];
    if (!isset($extMap[$mime])) return null;
    return [(string) file_get_contents($tmpPath), $extMap[$mime]];
}

/* Returns [binary, extension] or null on unsupported type. */
function processImage(string $tmpPath, string $mime): ?array {
    $extMap = ['image/jpeg' => 'jpg', 'image/png' => 'png', 'image/webp' => 'webp'];
    if (!isset($extMap[$mime])) return null;

    if (function_exists('imagecreatefromstring')) {
        $img = @imagecreatefromstring((string) file_get_contents($tmpPath));
        if ($img !== false) {
            if (imagesx($img) > 1600) {
                $resized = imagescale($img, 1600);
                if ($resized !== false) { imagedestroy($img); $img = $resized; }
            }
            ob_start();
            imagejpeg($img, null, 82);
            $bin = (string) ob_get_clean();
            imagedestroy($img);
            return [$bin, 'jpg'];
        }
    }
    return [(string) file_get_contents($tmpPath), $extMap[$mime]];
}

/* Human-readable upload failure from $_FILES['x']['error']; '' when OK or absent. */
function uploadError(array $f): string {
    return match ((int) ($f['error'] ?? UPLOAD_ERR_NO_FILE)) {
        UPLOAD_ERR_OK, UPLOAD_ERR_NO_FILE => '',
        UPLOAD_ERR_INI_SIZE, UPLOAD_ERR_FORM_SIZE => 'the file is too large for the server',
        UPLOAD_ERR_PARTIAL => 'the upload was interrupted — check the connection and try again',
        UPLOAD_ERR_NO_TMP_DIR, UPLOAD_ERR_CANT_WRITE => 'server storage error',
        default => 'upload failed',
    };
}

// ---------- Auth ----------
if (isset($_GET['logout'])) {
    session_destroy();
    header('Location: panel.php');
    exit;
}

if (isset($_POST['action']) && $_POST['action'] === 'login') {
    if ($config && hash_equals((string) $config['panel_password'], (string) ($_POST['password'] ?? ''))) {
        session_regenerate_id(true);
        $_SESSION['ok'] = true;
        $_SESSION['csrf'] = bin2hex(random_bytes(16));
    } else {
        sleep(1);
        $err = 'Incorrect password.';
    }
}

$logged = !empty($_SESSION['ok']);

$csrfOk = function (): bool {
    return hash_equals((string) ($_SESSION['csrf'] ?? ''), (string) ($_POST['csrf'] ?? ''));
};

// ---------- Edit: load an existing article (?edit=<locale>/<slug>) ----------
$editing = null;
if ($logged && $config && isset($_GET['edit'])) {
    if (preg_match('#^(en|es|hi|ml)/([a-z0-9-]+)$#', (string) $_GET['edit'], $m)) {
        $file = ghGetFile($config, "src/content/news/{$m[1]}/{$m[2]}.md");
        if ($file) {
            [$fields, $body] = parseNewsFile($file['content']);
            $editing = ['locale' => $m[1], 'slug' => $m[2], 'fields' => $fields, 'body' => $body];
        } else {
            $err = 'Could not load that article from GitHub.';
        }
    }
}

// ---------- Delete ----------
if ($logged && isset($_POST['action']) && $_POST['action'] === 'delete') {
    if (!$csrfOk()) {
        $err = 'Session expired — please try again.';
    } elseif (!$config) {
        $err = 'Panel is not configured yet.';
    } else {
        $path = (string) ($_POST['path'] ?? '');
        if (!preg_match('#^src/content/news/(en|es|hi|ml)/[a-z0-9-]+\.md$#', $path)) {
            $err = 'Invalid article path.';
        } else {
            // If the article uses a panel-managed photo, remove it too (best effort).
            $file = ghGetFile($config, $path);
            $mediaPaths = [];
            if ($file) {
                [$fields] = parseNewsFile($file['content']);
                if (preg_match('#^/images/news/[a-z0-9-]+\.(jpg|png|webp)$#', $fields['image'])) {
                    $mediaPaths[] = 'public' . $fields['image'];
                }
                if (preg_match('#^/videos/[a-z0-9-]+\.(mp4|webm|mov)$#', $fields['video'])) {
                    $mediaPaths[] = 'public' . $fields['video'];
                }
            }
            [$ok, $delErr] = ghDelete($config, $path, "news: delete {$path}");
            if (!$ok) {
                $err = $delErr;
            } else {
                foreach ($mediaPaths as $mp) ghDelete($config, $mp, "news: delete media for {$path}");
                $msg = "Deleted \"{$path}\". The site will update in about 3-5 minutes.";
            }
        }
    }
}

// ---------- Publish / Update ----------
if ($logged && isset($_POST['action']) && $_POST['action'] === 'publish') {
    if (!$csrfOk()) {
        $err = 'Session expired — please try again.';
    } elseif (!$config) {
        $err = 'Panel is not configured yet. Ask Luis to create panel-config.php (see docs/PANEL.md).';
    } else {
        // Edit mode: keep the original slug + locale so the same file is updated.
        $editSlug = (string) ($_POST['edit_slug'] ?? '');
        $editLocale = (string) ($_POST['edit_locale'] ?? '');
        $isEdit = $editSlug !== '' && preg_match('/^[a-z0-9-]+$/', $editSlug) && isset(LOCALES[$editLocale]);
        $origImage = (string) ($_POST['orig_image'] ?? '');
        if (!preg_match('#^/images/[a-zA-Z0-9_/.-]+$#', $origImage)) $origImage = '';
        $origVideo = (string) ($_POST['orig_video'] ?? '');
        if (!preg_match('#^(/videos/|https?://)#i', $origVideo)) $origVideo = '';

        $locale = $isEdit ? $editLocale : (string) ($_POST['locale'] ?? 'en');
        $title = trim((string) ($_POST['title'] ?? ''));
        $category = in_array($_POST['category'] ?? '', CATEGORIES, true) ? (string) $_POST['category'] : 'General';
        $description = trim((string) ($_POST['description'] ?? ''));
        $imageAlt = trim((string) ($_POST['image_alt'] ?? ''));
        $body = trim((string) ($_POST['body'] ?? ''));
        $date = preg_match('/^\d{4}-\d{2}-\d{2}$/', (string) ($_POST['date'] ?? ''))
            ? (string) $_POST['date'] : gmdate('Y-m-d');

        $photoErr = !empty($_FILES['photo']) ? uploadError($_FILES['photo']) : '';
        $videoErr = !empty($_FILES['video']) ? uploadError($_FILES['video']) : '';
        $hasPhoto = $photoErr === '' && !empty($_FILES['photo']) && $_FILES['photo']['error'] === UPLOAD_ERR_OK;
        $photoMissing = !$hasPhoto && (!$isEdit || $origImage === '');
        $hasVideo = $videoErr === '' && !empty($_FILES['video']) && $_FILES['video']['error'] === UPLOAD_ERR_OK;
        $videoUrl = trim((string) ($_POST['video_url'] ?? ''));

        if (!isset(LOCALES[$locale])) $err = 'Please choose a valid language.';
        elseif ($title === '' || $body === '' || $description === '' || $imageAlt === '') {
            $err = 'Please fill in every field.';
        } elseif ($photoErr !== '') {
            $err = 'The photo could not be uploaded: ' . $photoErr;
        } elseif ($hasPhoto && $_FILES['photo']['size'] > MAX_UPLOAD) {
            $err = 'The photo is too large (max 12 MB).';
        } elseif ($photoMissing) {
            $err = 'Please attach a photo (JPG, PNG or WebP, up to 12 MB).';
        } elseif ($videoErr !== '') {
            $err = 'The video could not be uploaded: ' . $videoErr;
        } elseif ($hasVideo && $_FILES['video']['size'] > MAX_VIDEO_UPLOAD) {
            $err = 'The video is too large (max 45 MB) — for longer videos, upload to YouTube and paste the link instead.';
        } elseif ($videoUrl !== '' && !preg_match('#^https?://(www\.)?(youtube\.com|youtu\.be|m\.youtube\.com|vimeo\.com|player\.vimeo\.com|instagram\.com)/#i', $videoUrl)) {
            $err = 'The video link must be a YouTube, Vimeo or Instagram URL.';
        } else {
            @set_time_limit(300); // media commits to GitHub can be slow
            $slug = $isEdit ? $editSlug : slugify($title);
            $imgWebPath = $origImage;
            $imgRepoPath = null;
            $imgBin = null;
            $video = $origVideo;
            $vidRepoPath = null;
            $vidBin = null;

            if ($hasVideo) {
                $mime = (string) (new finfo(FILEINFO_MIME_TYPE))->file($_FILES['video']['tmp_name']);
                $vid = processVideo($_FILES['video']['tmp_name'], $mime);
                if (!$vid) {
                    $err = 'The video must be MP4, WebM or MOV.';
                } else {
                    [$vidBin, $vExt] = $vid;
                    $vidRepoPath = "public/videos/{$slug}.{$vExt}";
                    $video = "/videos/{$slug}.{$vExt}";
                }
            } elseif ($videoUrl !== '') {
                $video = $videoUrl;
            }

            if ($err === '' && $hasPhoto) {
                $mime = (string) (new finfo(FILEINFO_MIME_TYPE))->file($_FILES['photo']['tmp_name']);
                $image = processImage($_FILES['photo']['tmp_name'], $mime);
                if (!$image) {
                    $err = 'The photo must be a JPG, PNG or WebP image.';
                } else {
                    [$imgBin, $ext] = $image;
                    $imgRepoPath = "public/images/news/{$slug}.{$ext}";
                    $imgWebPath = "/images/news/{$slug}.{$ext}";
                }
            }

            if ($err === '') {
                $md = "---\n"
                    . 'title: ' . yamlQuote($title) . "\n"
                    . "date: {$date}T00:00:00.000Z\n"
                    . "category: {$category}\n"
                    . "image: {$imgWebPath}\n"
                    . 'imageAlt: ' . yamlQuote($imageAlt) . "\n"
                    . 'description: ' . yamlQuote($description) . "\n"
                    . ($video !== '' ? "video: {$video}\n" : '')
                    . "---\n\n" . $body . "\n";

                if ($imgRepoPath) {
                    [$okImg, $errImg] = ghCommit($config, $imgRepoPath, (string) $imgBin, "news: photo for {$slug}");
                    if (!$okImg) $err = $errImg;
                }
                if ($err === '' && $vidRepoPath) {
                    [$okVid, $errVid] = ghCommit($config, $vidRepoPath, (string) $vidBin, "news: video for {$slug}");
                    if (!$okVid) $err = $errVid;
                }
                if ($err === '') {
                    [$okMd, $errMd] = ghCommit($config, "src/content/news/{$locale}/{$slug}.md", $md, ($isEdit ? 'news: update ' : 'news: ') . $title);
                    if ($okMd) {
                        $base = LOCALE_NEWS_BASE[$locale];
                        $verb = $isEdit ? 'Updated' : 'Published';
                        $msg = "{$verb} \"{$title}\". It will appear at https://hospitalarias.in{$base} in about 3-5 minutes.";
                    } else {
                        $err = $errMd;
                    }
                }
            }
        }
    }
}

// ---------- Manage list ----------
$articles = ($logged && $config) ? ghListNews($config) : [];
$articlesByLocale = [];
foreach ($articles as $a) $articlesByLocale[$a['locale']][] = $a;
$editKey = $editing ? $editing['locale'] . '/' . $editing['slug'] : '';

// Form values: defaults <- article being edited <- what the user just typed
// (so a failed publish never wipes their work).
$form = [
    'locale' => 'en', 'date' => gmdate('Y-m-d'), 'title' => '', 'category' => '',
    'description' => '', 'imageAlt' => '', 'body' => '', 'video_url' => '',
];
if ($editing) {
    $form = array_merge($form, [
        'locale' => $editing['locale'],
        'date' => $editing['fields']['date'],
        'title' => $editing['fields']['title'],
        'category' => $editing['fields']['category'],
        'description' => $editing['fields']['description'],
        'imageAlt' => $editing['fields']['imageAlt'],
        'body' => $editing['body'],
        'video_url' => str_starts_with($editing['fields']['video'], 'http') ? $editing['fields']['video'] : '',
    ]);
}
if ($err !== '' && (($_POST['action'] ?? '') === 'publish')) {
    foreach ([
        'locale' => 'locale', 'date' => 'date', 'title' => 'title',
        'category' => 'category', 'description' => 'description',
        'imageAlt' => 'image_alt', 'body' => 'body', 'video_url' => 'video_url',
    ] as $k => $postKey) {
        $v = trim((string) ($_POST[$postKey] ?? ''));
        if ($v !== '') $form[$k] = $v;
    }
}
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>News Panel — Benedict Menni Centre</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; background: #f4f2ef; color: #26221e; margin: 0; }
  a { color: #7a2e2e; }

  /* ---------- Sidebar layout (logged in) ---------- */
  .layout { display: flex; min-height: 100svh; }
  .side {
    width: 250px; flex-shrink: 0; background: #fff; border-right: 1px solid #e6e0d8;
    padding: 18px 14px; position: sticky; top: 0; height: 100svh; overflow-y: auto;
    display: flex; flex-direction: column; gap: 14px;
  }
  .side-brand { font-size: 1.05rem; font-weight: 800; margin: 0; }
  .side-brand span { display: block; font-size: .72rem; font-weight: 600; color: #6b655c; margin-top: 2px; }
  .btn-new {
    display: block; background: #7a2e2e; color: #fff; text-align: center; text-decoration: none;
    font-weight: 700; font-size: .92rem; padding: 11px; border-radius: 8px;
  }
  .btn-new:hover { background: #612525; }
  .side-label { font-size: .7rem; font-weight: 800; text-transform: uppercase; letter-spacing: .05em; color: #6b655c; margin: 6px 4px 6px; }
  .side-group { font-size: .72rem; font-weight: 700; color: #6b655c; text-transform: uppercase; letter-spacing: .05em; margin: 10px 4px 4px; }
  .side-item {
    display: flex; align-items: center; gap: 6px; padding: 8px 8px; border-radius: 8px;
    text-decoration: none; color: #26221e; font-size: .85rem; line-height: 1.25;
  }
  .side-item:hover { background: #f4f2ef; }
  .side-item.active { background: #f7ecec; color: #7a2e2e; font-weight: 700; }
  .side-item .slug { flex: 1; overflow: hidden; text-overflow: ellipsis; color: inherit; text-decoration: none; }
  .side-item.active .slug { color: #7a2e2e; }
  .side-item .view { font-size: .78rem; color: #6b655c; text-decoration: none; }
  .side-item .del {
    border: 0; background: none; color: #b0564f; cursor: pointer; font-size: .95rem;
    padding: 0 4px; line-height: 1;
  }
  .side-item .del:hover { color: #922; }
  .side-foot { margin-top: auto; padding-top: 12px; border-top: 1px solid #f0ece5; font-size: .82rem; display: flex; flex-direction: column; gap: 6px; }
  .side-foot a { text-decoration: none; }
  .side-empty { color: #6b655c; font-size: .85rem; margin: 4px; }

  .main { flex: 1; padding: 26px 20px 40px; display: flex; justify-content: center; align-items: flex-start; }
  .main .card { width: 100%; max-width: 620px; }

  /* ---------- Card / form ---------- */
  .card { background: #fff; border-radius: 14px; padding: 28px; box-shadow: 0 6px 24px rgba(0,0,0,.08); }
  .centered { min-height: 100svh; display: flex; align-items: center; justify-content: center; padding: 24px; }
  .centered .card { width: 100%; max-width: 420px; }
  h1 { font-size: 1.35rem; margin: 0 0 4px; }
  .sub { color: #6b655c; font-size: .9rem; margin: 0 0 20px; }
  label { display: block; font-weight: 600; font-size: .85rem; margin: 16px 0 4px; }
  input, select, textarea { width: 100%; padding: 11px 12px; border: 1px solid #d8d2c8; border-radius: 8px; font: inherit; font-size: 1rem; background: #fff; }
  input[readonly] { background: #f4f2ef; }
  textarea { min-height: 160px; resize: vertical; }
  .hint { font-size: .78rem; color: #6b655c; margin-top: 3px; }
  .card button[type=submit] { margin-top: 22px; width: 100%; padding: 13px; border: 0; border-radius: 8px; background: #7a2e2e; color: #fff; font-size: 1rem; font-weight: 700; cursor: pointer; }
  .card button[type=submit]:hover { background: #612525; }
  .ok { background: #e8f5e9; border: 1px solid #a5d6a7; color: #1b5e20; padding: 12px 14px; border-radius: 8px; margin-bottom: 16px; }
  .err { background: #fdecea; border: 1px solid #f5b7b1; color: #922; padding: 12px 14px; border-radius: 8px; margin-bottom: 16px; }
  .row { display: flex; gap: 12px; } .row > div { flex: 1; }
  .links { display: flex; justify-content: space-between; margin-top: 18px; font-size: .85rem; }
  form.inline { display: inline; margin: 0; }

  @media (max-width: 860px) {
    .layout { flex-direction: column; }
    .side {
      width: 100%; position: static; height: auto; max-height: none;
      border-right: 0; border-bottom: 1px solid #e6e0d8;
    }
    .side nav { max-height: 42svh; overflow-y: auto; }
    .main { padding: 18px 12px 32px; }
    .card { padding: 20px; }
  }
</style>
</head>
<body>

<?php if (!$logged): ?>
<div class="centered">
  <div class="card">
    <h1>News Panel</h1>
    <p class="sub">Benedict Menni Psychosocial Rehabilitation Centre</p>
    <?php if ($err): ?><div class="err"><?= e($err) ?></div><?php endif; ?>
    <form method="post">
      <input type="hidden" name="action" value="login">
      <label for="password">Password</label>
      <input type="password" id="password" name="password" required autofocus autocomplete="current-password">
      <button type="submit">Sign in</button>
    </form>
  </div>
</div>

<?php else: ?>
<div class="layout">
  <aside class="side">
    <p class="side-brand">News Panel<span>Benedict Menni Centre</span></p>
    <a class="btn-new" href="panel.php">+ New article</a>

    <nav aria-label="Existing articles">
      <p class="side-label">Articles</p>
      <?php if ($articlesByLocale): ?>
        <?php foreach ($articlesByLocale as $loc => $items): ?>
          <p class="side-group"><?= e(strtoupper($loc)) ?> — <?= e(LOCALES[$loc] ?? $loc) ?></p>
          <?php foreach ($items as $a):
            $key = $a['locale'] . '/' . $a['slug']; ?>
            <div class="side-item<?= $key === $editKey ? ' active' : '' ?>">
              <a class="slug" href="?edit=<?= e($key) ?>"><?= e($a['slug']) ?></a>
              <a class="view" href="https://hospitalarias.in<?= e(LOCALE_NEWS_BASE[$a['locale']]) . e($a['slug']) ?>/" target="_blank" rel="noopener" title="View on site">↗</a>
              <form class="inline" method="post" onsubmit="return confirm('Delete &quot;<?= e($a['slug']) ?>&quot; (<?= e($a['locale']) ?>)? This cannot be undone.');">
                <input type="hidden" name="action" value="delete">
                <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">
                <input type="hidden" name="path" value="<?= e($a['path']) ?>">
                <button type="submit" class="del" title="Delete">×</button>
              </form>
            </div>
          <?php endforeach; ?>
        <?php endforeach; ?>
      <?php else: ?>
        <p class="side-empty">No articles yet — publish the first one.</p>
      <?php endif; ?>
    </nav>

    <div class="side-foot">
      <a href="https://hospitalarias.in/en/news/" target="_blank" rel="noopener">View news page ↗</a>
      <a href="?logout=1">Sign out</a>
    </div>
  </aside>

  <main class="main">
    <div class="card">
      <h1><?= $editing ? 'Edit article' : 'New article' ?></h1>
      <p class="sub"><?= $editing
        ? 'Editing ' . e($editing['slug']) . '.md — the URL stays the same.'
        : 'Publish directly to the website (~3-5 min to appear).' ?></p>

      <?php if ($msg): ?><div class="ok"><?= e($msg) ?></div><?php endif; ?>
      <?php if ($err): ?><div class="err"><?= e($err) ?></div><?php endif; ?>

      <form method="post" enctype="multipart/form-data">
        <input type="hidden" name="action" value="publish">
        <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">
        <?php if ($editing): ?>
          <input type="hidden" name="edit_slug" value="<?= e($editing['slug']) ?>">
          <input type="hidden" name="edit_locale" value="<?= e($editing['locale']) ?>">
          <input type="hidden" name="orig_image" value="<?= e($editing['fields']['image']) ?>">
          <input type="hidden" name="orig_video" value="<?= e($editing['fields']['video']) ?>">
        <?php endif; ?>

        <div class="row">
          <div>
            <label for="locale">Article language</label>
            <?php if ($editing): ?>
              <input type="text" value="<?= e(LOCALES[$editing['locale']]) ?>" readonly>
            <?php else: ?>
              <select id="locale" name="locale">
                <?php foreach (LOCALES as $code => $label): ?>
                  <option value="<?= e($code) ?>" <?= $code === $form['locale'] ? 'selected' : '' ?>><?= e($label) ?></option>
                <?php endforeach; ?>
              </select>
            <?php endif; ?>
          </div>
          <div>
            <label for="date">Date</label>
            <input type="date" id="date" name="date" value="<?= e($form['date']) ?>">
          </div>
        </div>

        <label for="title">Title</label>
        <input type="text" id="title" name="title" required maxlength="140" value="<?= e($form['title']) ?>">

        <label for="category">Category</label>
        <select id="category" name="category">
          <?php
          $cats = CATEGORIES;
          $cur = $form['category'];
          if ($cur !== '' && !in_array($cur, $cats, true)) array_unshift($cats, $cur);
          foreach ($cats as $c): ?>
            <option <?= $c === $cur ? 'selected' : '' ?>><?= e($c) ?></option>
          <?php endforeach; ?>
        </select>

        <label for="description">Short description</label>
        <input type="text" id="description" name="description" required maxlength="200" value="<?= e($form['description']) ?>">
        <p class="hint">One or two sentences — shown on the news card.</p>

        <label for="photo">Photo</label>
        <input type="file" id="photo" name="photo" accept="image/jpeg,image/png,image/webp" <?= $editing ? '' : 'required' ?>>
        <p class="hint"><?= $editing ? 'Leave empty to keep the current photo.' : 'JPG, PNG or WebP, up to 12 MB. Large photos are resized automatically.' ?></p>
        <?php if ($editing && $editing['fields']['image'] !== ''): ?>
          <p class="hint">Current: <a href="https://hospitalarias.in<?= e($editing['fields']['image']) ?>" target="_blank" rel="noopener"><?= e($editing['fields']['image']) ?></a></p>
        <?php endif; ?>

        <label for="video_url">Video — YouTube, Vimeo or Instagram link (optional)</label>
        <input type="url" id="video_url" name="video_url" placeholder="https://youtube.com/watch?v=… or https://instagram.com/reel/…" value="<?= e($form['video_url']) ?>">
        <p class="hint">Paste a YouTube/Vimeo link, or an Instagram post/reel link to show it inside the article.</p>

        <label for="video">Or upload a video file</label>
        <input type="file" id="video" name="video" accept="video/mp4,video/webm,video/quicktime">
        <p class="hint">MP4 or WebM, max 45 MB. <?= $editing ? 'Leave empty to keep the current video.' : 'For longer videos use YouTube — faster and takes no space.' ?></p>
        <?php if ($editing && $editing['fields']['video'] !== ''): ?>
          <p class="hint">Current: <?= e($editing['fields']['video']) ?></p>
        <?php endif; ?>

        <label for="image_alt">Photo description</label>
        <input type="text" id="image_alt" name="image_alt" required maxlength="160" value="<?= e($form['imageAlt']) ?>">
        <p class="hint">Describe the photo for blind readers, e.g. "Residents at the garden workshop".</p>

        <label for="body">Article text</label>
        <textarea id="body" name="body" required><?= e($form['body']) ?></textarea>
        <p class="hint">Plain text. Leave an empty line between paragraphs.</p>

        <button type="submit"><?= $editing ? 'Update article' : 'Publish' ?></button>
      </form>
      <div class="links">
        <?php if ($editing): ?><a href="panel.php">+ New article</a><?php endif; ?>
        <a href="https://hospitalarias.in/en/news/" target="_blank" rel="noopener">View news page ↗</a>
        <a href="?logout=1">Sign out</a>
      </div>
    </div>
  </main>
</div>
<?php endif; ?>

</body>
</html>
