<?php
declare(strict_types=1);
// Long-lived session: writing an article can take a while.
session_set_cookie_params([
    'lifetime' => 8 * 3600,
    'path' => '/',
    'secure' => !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off',
    'httponly' => true,
    'samesite' => 'Lax',
]);
ini_set('session.gc_maxlifetime', (string) (8 * 3600));
session_start();

/*
 * News panel — publish, edit and delete articles + photos without external services.
 * Form -> commits markdown + image to GitHub -> GitHub Action redeploys the site (~3 min).
 *
 * Config file `panel-config.php` (generated by CI inside public_html; a manual copy
 * outside the web root takes precedence). See docs/PANEL.md.
 */

// Config search: ancestors of public_html first, webroot last — a file outside
// the web root (e.g. /home/<user>/panel-config.php) always wins over the
// CI-generated one that ships inside public_html.
$dir = __DIR__;
$dirs = [];
for ($i = 0; $i < 6 && $dir !== dirname($dir); $i++) {
    $dirs[] = $dir;
    $dir = dirname($dir);
}
$config = null;
foreach (array_reverse($dirs) as $d) {
    if (is_file($d . '/panel-config.php')) {
        $config = require $d . '/panel-config.php';
        break;
    }
}

const CATEGORIES = ['Campaigns', 'Vatican', 'Mission', 'Community', 'Events', 'General'];
const LOCALES = ['en' => 'English', 'es' => 'Español (Spanish)', 'hi' => 'हिन्दी (Hindi)', 'ml' => 'മലയാളം (Malayalam)'];
const LOCALE_NEWS_BASE = ['en' => '/en/news/', 'es' => '/es/noticias/', 'hi' => '/hi/samachar/', 'ml' => '/ml/varthakal/'];
const MONTHS = ['01' => 'Jan', '02' => 'Feb', '03' => 'Mar', '04' => 'Apr', '05' => 'May', '06' => 'Jun', '07' => 'Jul', '08' => 'Aug', '09' => 'Sep', '10' => 'Oct', '11' => 'Nov', '12' => 'Dec'];
const GALLERY_JSON = 'src/data/gallery.json';
const NOTICE_JSON = 'src/data/notice.json';
const NEWS_JSON = 'src/data/newsletters.json';
const HEROES_JSON = 'src/data/page-heroes.json';
const MAX_PDF = 20 * 1024 * 1024; // 20 MB newsletter PDFs
const HERO_SLOTS = ['home-main' => 'Home — main photo'];
const MAX_UPLOAD = 12 * 1024 * 1024; // 12 MB photos
const MAX_VIDEO_UPLOAD = 45 * 1024 * 1024; // 45 MB videos — bigger belongs on YouTube

$msg = '';
$err = '';

function e(string $s): string { return htmlspecialchars($s, ENT_QUOTES, 'UTF-8'); }

function slugify(string $t): string {
    $ascii = function_exists('iconv') ? (iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $t) ?: '') : '';
    $s = strtolower(trim(preg_replace('/[^a-zA-Z0-9]+/', '-', $ascii !== '' ? $ascii : $t) ?? '', '-'));
    return $s !== '' ? substr($s, 0, 60) : 'article-' . gmdate('Ymd-Hi');
}

function yamlQuote(string $s): string {
    return "'" . str_replace("'", "''", trim($s)) . "'";
}

function httpRequest(string $method, string $url, array $headers, ?string $body = null, int $timeout = 30): array {
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_CUSTOMREQUEST => $method,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_TIMEOUT => $timeout,
    ]);
    if ($body !== null) curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
    $resp = curl_exec($ch);
    $code = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
    curl_close($ch);
    return [$code, is_string($resp) ? $resp : ''];
}

function ghHeaders(array $config): array {
    return [
        'Authorization: Bearer ' . $config['github_token'],
        'Accept: application/vnd.github+json',
        'X-GitHub-Api-Version: 2022-11-28',
        'User-Agent: hospitalarias-panel',
        'Content-Type: application/json',
    ];
}

function ghApiUrl(array $config, string $path): string {
    return 'https://api.github.com/repos/' . $config['github_repo'] . '/contents/'
        . implode('/', array_map('rawurlencode', explode('/', $path)));
}

/* Read one repo file. Returns ['content'=>, 'sha'=>] or null. */
function ghGetFile(array $config, string $path): ?array {
    [$code, $body] = httpRequest('GET', ghApiUrl($config, $path) . '?ref=' . rawurlencode($config['github_branch']), ghHeaders($config));
    if ($code !== 200) return null;
    $data = json_decode($body, true);
    if (!is_array($data) || !isset($data['sha'])) return null;
    $raw = isset($data['content']) ? base64_decode(str_replace("\n", '', (string) $data['content'])) : '';
    return ['content' => is_string($raw) ? $raw : '', 'sha' => (string) $data['sha']];
}

/* Commit (or update) one file in the repo. Returns [ok, errorMessage]. */
function ghCommit(array $config, string $path, string $binary, string $message): array {
    $api = ghApiUrl($config, $path);
    $headers = ghHeaders($config);

    $sha = null;
    [$code, $body] = httpRequest('GET', $api . '?ref=' . rawurlencode($config['github_branch']), $headers);
    if ($code === 200) {
        $sha = json_decode($body, true)['sha'] ?? null;
    }

    $payload = [
        'message' => $message,
        'content' => base64_encode($binary),
        'branch' => $config['github_branch'],
    ];
    if ($sha) $payload['sha'] = $sha;

    // Videos push a big base64 payload — give the PUT more time.
    [$code, $body] = httpRequest('PUT', $api, $headers, json_encode($payload), strlen($binary) > 4 * 1024 * 1024 ? 120 : 30);
    if ($code === 200 || $code === 201) return [true, ''];
    $detail = json_decode($body, true)['message'] ?? $body;
    return [false, "GitHub error {$code} on {$path}: {$detail}"];
}

/* Delete one repo file. Returns [ok, errorMessage]. */
function ghDelete(array $config, string $path, string $message): array {
    $file = ghGetFile($config, $path);
    if (!$file) return [false, "Could not read {$path} on GitHub."];
    [$code, $body] = httpRequest('DELETE', ghApiUrl($config, $path), ghHeaders($config), json_encode([
        'message' => $message,
        'sha' => $file['sha'],
        'branch' => $config['github_branch'],
    ]));
    if ($code === 200) return [true, ''];
    $detail = json_decode($body, true)['message'] ?? $body;
    return [false, "GitHub error {$code} deleting {$path}: {$detail}"];
}

/* List markdown articles for every locale: [['locale','slug','path'], ...] */
function ghListNews(array $config): array {
    $out = [];
    foreach (array_keys(LOCALES) as $loc) {
        [$code, $body] = httpRequest('GET', ghApiUrl($config, "src/content/news/{$loc}") . '?ref=' . rawurlencode($config['github_branch']), ghHeaders($config));
        if ($code !== 200) continue;
        foreach ((json_decode($body, true) ?: []) as $item) {
            if (($item['type'] ?? '') === 'file' && str_ends_with((string) $item['name'], '.md')) {
                $out[] = ['locale' => $loc, 'slug' => substr($item['name'], 0, -3), 'path' => (string) $item['path']];
            }
        }
    }
    return $out;
}

/* Fetch many repo files in parallel via curl_multi. Returns [path => content]. */
function ghGetFiles(array $config, array $paths): array {
    $mh = curl_multi_init();
    $handles = [];
    foreach (array_slice($paths, 0, 80) as $path) {
        $ch = curl_init(ghApiUrl($config, $path) . '?ref=' . rawurlencode($config['github_branch']));
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_HTTPHEADER => ghHeaders($config),
            CURLOPT_TIMEOUT => 30,
        ]);
        curl_multi_add_handle($mh, $ch);
        $handles[$path] = $ch;
    }
    $running = 0;
    do {
        $st = curl_multi_exec($mh, $running);
        if ($running) curl_multi_select($mh);
    } while ($running > 0 && $st === CURLM_OK);
    $out = [];
    foreach ($handles as $path => $ch) {
        if ((int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE) === 200) {
            $data = json_decode((string) curl_multi_getcontent($ch), true);
            if (isset($data['content'])) {
                $out[$path] = (string) base64_decode(str_replace("\n", '', (string) $data['content']));
            }
        }
        curl_multi_remove_handle($mh, $ch);
        curl_close($ch);
    }
    curl_multi_close($mh);
    return $out;
}

/* Split a news markdown file into frontmatter fields + body. */
function parseNewsFile(string $md): array {
    $fields = ['title' => '', 'date' => '', 'category' => 'General', 'image' => '', 'imageAlt' => '', 'description' => '', 'video' => ''];
    $body = $md;
    if (preg_match('/^---\R(.*?)\R---\R?(.*)$/s', $md, $m)) {
        $body = trim($m[2]);
        foreach (preg_split('/\R/', $m[1]) ?: [] as $line) {
            if (!preg_match('/^(\w+):\s*(.*)$/', $line, $kv)) continue;
            [$k, $v] = [$kv[1], trim($kv[2])];
            if (strlen($v) >= 2 && $v[0] === "'" && str_ends_with($v, "'")) {
                $v = str_replace("''", "'", substr($v, 1, -1));
            } elseif (strlen($v) >= 2 && $v[0] === '"' && str_ends_with($v, '"')) {
                $v = str_replace('\\"', '"', substr($v, 1, -1));
            }
            if (array_key_exists($k, $fields)) $fields[$k] = $v;
        }
    }
    $fields['date'] = substr($fields['date'], 0, 10);
    return [$fields, $body];
}

/* Returns [binary, extension] or null on unsupported type. Videos are stored
   as-is — no transcoding on shared hosting. */
function processVideo(string $tmpPath, string $mime): ?array {
    $extMap = ['video/mp4' => 'mp4', 'video/webm' => 'webm', 'video/quicktime' => 'mov'];
    if (!isset($extMap[$mime])) return null;
    return [(string) file_get_contents($tmpPath), $extMap[$mime]];
}

/* Returns [binary, extension] or null on unsupported type. */
function processImage(string $tmpPath, string $mime): ?array {
    $extMap = ['image/jpeg' => 'jpg', 'image/png' => 'png', 'image/webp' => 'webp'];
    if (!isset($extMap[$mime])) return null;

    if (function_exists('imagecreatefromstring')) {
        $img = @imagecreatefromstring((string) file_get_contents($tmpPath));
        if ($img !== false) {
            if (imagesx($img) > 1600) {
                $resized = imagescale($img, 1600);
                if ($resized !== false) { imagedestroy($img); $img = $resized; }
            }
            ob_start();
            imagejpeg($img, null, 82);
            $bin = (string) ob_get_clean();
            imagedestroy($img);
            return [$bin, 'jpg'];
        }
    }
    return [(string) file_get_contents($tmpPath), $extMap[$mime]];
}

/* Read a JSON file from the repo; [] when missing/invalid. */
function ghGetJsonFile(array $config, string $path): array {
    $f = ghGetFile($config, $path);
    if (!$f) return [];
    $d = json_decode($f['content'], true);
    return is_array($d) ? $d : [];
}

/* Human-readable upload failure from $_FILES['x']['error']; '' when OK or absent. */
function uploadError(array $f): string {
    return match ((int) ($f['error'] ?? UPLOAD_ERR_NO_FILE)) {
        UPLOAD_ERR_OK, UPLOAD_ERR_NO_FILE => '',
        UPLOAD_ERR_INI_SIZE, UPLOAD_ERR_FORM_SIZE => 'the file is too large for the server',
        UPLOAD_ERR_PARTIAL => 'the upload was interrupted — check the connection and try again',
        UPLOAD_ERR_NO_TMP_DIR, UPLOAD_ERR_CANT_WRITE => 'server storage error',
        default => 'upload failed',
    };
}

// ---------- Auth ----------
if (isset($_GET['logout'])) {
    session_destroy();
    header('Location: panel.php');
    exit;
}

if (isset($_POST['action']) && $_POST['action'] === 'login') {
    if ($config && hash_equals((string) $config['panel_password'], (string) ($_POST['password'] ?? ''))) {
        session_regenerate_id(true);
        $_SESSION['ok'] = true;
        $_SESSION['csrf'] = bin2hex(random_bytes(16));
    } else {
        sleep(1);
        $err = 'Incorrect password.';
    }
}

$logged = !empty($_SESSION['ok']);

$csrfOk = function (): bool {
    return hash_equals((string) ($_SESSION['csrf'] ?? ''), (string) ($_POST['csrf'] ?? ''));
};

// ---------- Edit: load an existing article (?edit=<locale>/<slug>) ----------
$editing = null;
if ($logged && $config && isset($_GET['edit'])) {
    if (preg_match('#^(en|es|hi|ml)/([a-z0-9-]+)$#', (string) $_GET['edit'], $m)) {
        $file = ghGetFile($config, "src/content/news/{$m[1]}/{$m[2]}.md");
        if ($file) {
            [$fields, $body] = parseNewsFile($file['content']);
            $editing = ['locale' => $m[1], 'slug' => $m[2], 'fields' => $fields, 'body' => $body];
        } else {
            $err = 'Could not load that article from GitHub.';
        }
    }
}

// ---------- Delete ----------
if ($logged && isset($_POST['action']) && $_POST['action'] === 'delete') {
    if (!$csrfOk()) {
        $err = 'Session expired — please try again.';
    } elseif (!$config) {
        $err = 'Panel is not configured yet.';
    } else {
        $path = (string) ($_POST['path'] ?? '');
        if (!preg_match('#^src/content/news/(en|es|hi|ml)/[a-z0-9-]+\.md$#', $path)) {
            $err = 'Invalid article path.';
        } else {
            // If the article uses a panel-managed photo, remove it too (best effort).
            $file = ghGetFile($config, $path);
            $mediaPaths = [];
            if ($file) {
                [$fields] = parseNewsFile($file['content']);
                if (preg_match('#^/images/news/[a-z0-9-]+\.(jpg|png|webp)$#', $fields['image'])) {
                    $mediaPaths[] = 'public' . $fields['image'];
                }
                if (preg_match('#^/videos/[a-z0-9-]+\.(mp4|webm|mov)$#', $fields['video'])) {
                    $mediaPaths[] = 'public' . $fields['video'];
                }
            }
            [$ok, $delErr] = ghDelete($config, $path, "news: delete {$path}");
            if (!$ok) {
                $err = $delErr;
            } else {
                foreach ($mediaPaths as $mp) ghDelete($config, $mp, "news: delete media for {$path}");
                $msg = "Deleted \"{$path}\". The site will update in about 3-5 minutes.";
            }
        }
    }
}

// ---------- Gallery photos ----------
if ($logged && isset($_POST['action']) && str_starts_with((string) $_POST['action'], 'gallery_')) {
    if (!$csrfOk()) {
        $err = 'Session expired — please try again.';
    } elseif (!$config) {
        $err = 'Panel is not configured yet.';
    } else {
        @set_time_limit(300);
        $items = ghGetJsonFile($config, GALLERY_JSON);

        if ($_POST['action'] === 'gallery_add') {
            $caption = trim((string) ($_POST['caption'] ?? ''));
            $fileErr = !empty($_FILES['photo']) ? uploadError($_FILES['photo']) : '';
            $hasFile = !empty($_FILES['photo']) && $_FILES['photo']['error'] === UPLOAD_ERR_OK;
            if ($fileErr !== '') {
                $err = 'The photo could not be uploaded: ' . $fileErr;
            } elseif (!$hasFile) {
                $err = 'Please choose a photo.';
            } elseif ($_FILES['photo']['size'] > MAX_UPLOAD) {
                $err = 'The photo is too large (max 12 MB).';
            } elseif ($caption === '') {
                $err = 'Please write a caption — what is happening in the photo?';
            } else {
                $mime = (string) (new finfo(FILEINFO_MIME_TYPE))->file($_FILES['photo']['tmp_name']);
                $image = processImage($_FILES['photo']['tmp_name'], $mime);
                if (!$image) {
                    $err = 'The photo must be a JPG, PNG or WebP image.';
                } else {
                    [$bin, $ext] = $image;
                    $base = slugify($caption);
                    $slug = $base;
                    $i = 2;
                    $used = array_column($items, 'src');
                    while (in_array("/images/gallery/{$slug}.{$ext}", $used, true)) $slug = $base . '-' . $i++;
                    $src = "/images/gallery/{$slug}.{$ext}";
                    [$okImg, $errImg] = ghCommit($config, 'public' . $src, (string) $bin, "gallery: {$caption}");
                    if (!$okImg) {
                        $err = $errImg;
                    } else {
                        array_unshift($items, ['src' => $src, 'alt' => $caption]);
                        [$okJ, $errJ] = ghCommit($config, GALLERY_JSON, json_encode($items, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . "\n", 'gallery: index update');
                        if ($okJ) $msg = 'Photo added — it will appear on the gallery page in about 3-5 minutes.';
                        else $err = $errJ;
                    }
                }
            }
        } elseif ($_POST['action'] === 'gallery_delete') {
            $src = (string) ($_POST['src'] ?? '');
            $keep = array_values(array_filter($items, fn($it) => ($it['src'] ?? '') !== $src));
            if (!preg_match('#^/images/gallery/[a-z0-9-]+\.(jpg|png|webp)$#', $src)) {
                $err = 'Invalid photo.';
            } elseif (count($keep) === count($items)) {
                $err = 'That photo is not in the gallery index.';
            } else {
                [$okJ, $errJ] = ghCommit($config, GALLERY_JSON, json_encode($keep, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . "\n", 'gallery: remove photo');
                if (!$okJ) {
                    $err = $errJ;
                } else {
                    ghDelete($config, 'public' . $src, 'gallery: delete photo'); // best effort
                    $msg = 'Photo removed. The gallery updates in about 3-5 minutes.';
                }
            }
        }
    }
}

// ---------- Announcement bar ----------
if ($logged && isset($_POST['action']) && $_POST['action'] === 'notice_save') {
    if (!$csrfOk()) {
        $err = 'Session expired — please try again.';
    } elseif (!$config) {
        $err = 'Panel is not configured yet.';
    } else {
        $href = trim((string) ($_POST['href'] ?? ''));
        if ($href !== '' && !preg_match('#^(https?://|/)[^\s]+$#i', $href)) $href = '';
        $notice = [
            'enabled' => !empty($_POST['enabled']),
            'text' => trim((string) ($_POST['text'] ?? '')),
            'href' => $href,
        ];
        [$ok, $errN] = ghCommit($config, NOTICE_JSON, json_encode($notice, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . "\n", 'site: announcement update');
        if ($ok) $msg = $notice['enabled'] ? 'Announcement is now ON — visible in ~3-5 minutes.' : 'Announcement is OFF — it disappears in ~3-5 minutes.';
        else $err = $errN;
    }
}

// ---------- Newsletter PDFs ----------
if ($logged && isset($_POST['action']) && str_starts_with((string) $_POST['action'], 'newsletter_')) {
    if (!$csrfOk()) {
        $err = 'Session expired — please try again.';
    } elseif (!$config) {
        $err = 'Panel is not configured yet.';
    } else {
        @set_time_limit(300);
        $items = ghGetJsonFile($config, NEWS_JSON);

        if ($_POST['action'] === 'newsletter_add') {
            $title = trim((string) ($_POST['title'] ?? ''));
            $date = preg_match('/^\d{4}-\d{2}-\d{2}$/', (string) ($_POST['date'] ?? '')) ? (string) $_POST['date'] : gmdate('Y-m-d');
            $fileErr = !empty($_FILES['pdf']) ? uploadError($_FILES['pdf']) : '';
            $hasFile = !empty($_FILES['pdf']) && $_FILES['pdf']['error'] === UPLOAD_ERR_OK;
            if ($fileErr !== '') {
                $err = 'The PDF could not be uploaded: ' . $fileErr;
            } elseif (!$hasFile) {
                $err = 'Please choose a PDF file.';
            } elseif ($_FILES['pdf']['size'] > MAX_PDF) {
                $err = 'The PDF is too large (max 20 MB).';
            } elseif ($title === '') {
                $err = 'Please write a title, e.g. "Newsletter — January 2027".';
            } elseif ((string) (new finfo(FILEINFO_MIME_TYPE))->file($_FILES['pdf']['tmp_name']) !== 'application/pdf') {
                $err = 'The file must be a PDF.';
            } else {
                $base = slugify($title);
                $slug = $base;
                $i = 2;
                $used = array_column($items, 'file');
                while (in_array("/newsletters/{$slug}.pdf", $used, true)) $slug = $base . '-' . $i++;
                $path = "/newsletters/{$slug}.pdf";
                [$okF, $errF] = ghCommit($config, 'public' . $path, (string) file_get_contents($_FILES['pdf']['tmp_name']), "newsletter: {$title}");
                if (!$okF) {
                    $err = $errF;
                } else {
                    array_unshift($items, ['file' => $path, 'title' => $title, 'date' => $date]);
                    [$okJ, $errJ] = ghCommit($config, NEWS_JSON, json_encode($items, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . "\n", 'newsletter: index update');
                    if ($okJ) $msg = 'Newsletter added — listed on the newsletter page in ~3-5 minutes.';
                    else $err = $errJ;
                }
            }
        } elseif ($_POST['action'] === 'newsletter_delete') {
            $file = (string) ($_POST['file'] ?? '');
            $keep = array_values(array_filter($items, fn($it) => ($it['file'] ?? '') !== $file));
            if (!preg_match('#^/newsletters/[a-z0-9-]+\.pdf$#', $file)) {
                $err = 'Invalid file.';
            } elseif (count($keep) === count($items)) {
                $err = 'That newsletter is not in the index.';
            } else {
                [$okJ, $errJ] = ghCommit($config, NEWS_JSON, json_encode($keep, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . "\n", 'newsletter: remove');
                if (!$okJ) {
                    $err = $errJ;
                } else {
                    ghDelete($config, 'public' . $file, 'newsletter: delete pdf'); // best effort
                    $msg = 'Newsletter removed. The page updates in ~3-5 minutes.';
                }
            }
        }
    }
}

// ---------- Page hero photos ----------
if ($logged && isset($_POST['action']) && str_starts_with((string) $_POST['action'], 'hero_')) {
    if (!$csrfOk()) {
        $err = 'Session expired — please try again.';
    } elseif (!$config) {
        $err = 'Panel is not configured yet.';
    } else {
        @set_time_limit(300);
        $heroes = ghGetJsonFile($config, HEROES_JSON);
        $slot = (string) ($_POST['slot'] ?? '');

        if (!isset(HERO_SLOTS[$slot])) {
            $err = 'Unknown page photo.';
        } elseif ($_POST['action'] === 'hero_reset') {
            unset($heroes[$slot]);
            [$okJ, $errJ] = ghCommit($config, HEROES_JSON, json_encode($heroes, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . "\n", 'site: reset page photo');
            if ($okJ) $msg = 'Photo reset to the original. Live in ~3-5 minutes.';
            else $err = $errJ;
        } elseif ($_POST['action'] === 'hero_save') {
            $fileErr = !empty($_FILES['photo']) ? uploadError($_FILES['photo']) : '';
            $hasFile = !empty($_FILES['photo']) && $_FILES['photo']['error'] === UPLOAD_ERR_OK;
            if ($fileErr !== '') {
                $err = 'The photo could not be uploaded: ' . $fileErr;
            } elseif (!$hasFile) {
                $err = 'Please choose a photo.';
            } elseif ($_FILES['photo']['size'] > MAX_UPLOAD) {
                $err = 'The photo is too large (max 12 MB).';
            } else {
                $mime = (string) (new finfo(FILEINFO_MIME_TYPE))->file($_FILES['photo']['tmp_name']);
                $image = processImage($_FILES['photo']['tmp_name'], $mime);
                if (!$image) {
                    $err = 'The photo must be a JPG, PNG or WebP image.';
                } else {
                    [$bin] = $image;
                    $src = "/images/pages/{$slot}.jpg";
                    [$okImg, $errImg] = ghCommit($config, 'public' . $src, (string) $bin, "site: photo for {$slot}");
                    if (!$okImg) {
                        $err = $errImg;
                    } else {
                        $heroes[$slot] = $src;
                        [$okJ, $errJ] = ghCommit($config, HEROES_JSON, json_encode($heroes, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . "\n", 'site: page photo update');
                        if ($okJ) $msg = 'Photo changed — visible in ~3-5 minutes.';
                        else $err = $errJ;
                    }
                }
            }
        }
    }
}

// ---------- Publish / Update ----------
if ($logged && isset($_POST['action']) && $_POST['action'] === 'publish') {
    if (!$csrfOk()) {
        $err = 'Session expired — please try again.';
    } elseif (!$config) {
        $err = 'Panel is not configured yet. Ask Luis to create panel-config.php (see docs/PANEL.md).';
    } else {
        // Edit mode: keep the original slug + locale so the same file is updated.
        $editSlug = (string) ($_POST['edit_slug'] ?? '');
        $editLocale = (string) ($_POST['edit_locale'] ?? '');
        $isEdit = $editSlug !== '' && preg_match('/^[a-z0-9-]+$/', $editSlug) && isset(LOCALES[$editLocale]);
        $origImage = (string) ($_POST['orig_image'] ?? '');
        if (!preg_match('#^/images/[a-zA-Z0-9_/.-]+$#', $origImage)) $origImage = '';
        $origVideo = (string) ($_POST['orig_video'] ?? '');
        if (!preg_match('#^(/videos/|https?://)#i', $origVideo)) $origVideo = '';

        $locale = $isEdit ? $editLocale : (string) ($_POST['locale'] ?? 'en');
        $title = trim((string) ($_POST['title'] ?? ''));
        $category = in_array($_POST['category'] ?? '', CATEGORIES, true) ? (string) $_POST['category'] : 'General';
        $description = trim((string) ($_POST['description'] ?? ''));
        $imageAlt = trim((string) ($_POST['image_alt'] ?? ''));
        $body = trim((string) ($_POST['body'] ?? ''));
        $date = preg_match('/^\d{4}-\d{2}-\d{2}$/', (string) ($_POST['date'] ?? ''))
            ? (string) $_POST['date'] : gmdate('Y-m-d');

        $photoErr = !empty($_FILES['photo']) ? uploadError($_FILES['photo']) : '';
        $videoErr = !empty($_FILES['video']) ? uploadError($_FILES['video']) : '';
        $hasPhoto = $photoErr === '' && !empty($_FILES['photo']) && $_FILES['photo']['error'] === UPLOAD_ERR_OK;
        $photoMissing = !$hasPhoto && (!$isEdit || $origImage === '');
        $hasVideo = $videoErr === '' && !empty($_FILES['video']) && $_FILES['video']['error'] === UPLOAD_ERR_OK;
        $videoUrl = trim((string) ($_POST['video_url'] ?? ''));

        if (!isset(LOCALES[$locale])) $err = 'Please choose a valid language.';
        elseif ($title === '' || $body === '' || $description === '' || $imageAlt === '') {
            $err = 'Please fill in every field.';
        } elseif ($photoErr !== '') {
            $err = 'The photo could not be uploaded: ' . $photoErr;
        } elseif ($hasPhoto && $_FILES['photo']['size'] > MAX_UPLOAD) {
            $err = 'The photo is too large (max 12 MB).';
        } elseif ($photoMissing) {
            $err = 'Please attach a photo (JPG, PNG or WebP, up to 12 MB).';
        } elseif ($videoErr !== '') {
            $err = 'The video could not be uploaded: ' . $videoErr;
        } elseif ($hasVideo && $_FILES['video']['size'] > MAX_VIDEO_UPLOAD) {
            $err = 'The video is too large (max 45 MB) — for longer videos, upload to YouTube and paste the link instead.';
        } elseif ($videoUrl !== '' && !preg_match('#^https?://(www\.)?(youtube\.com|youtu\.be|m\.youtube\.com|vimeo\.com|player\.vimeo\.com|instagram\.com)/#i', $videoUrl)) {
            $err = 'The video link must be a YouTube, Vimeo or Instagram URL.';
        } else {
            @set_time_limit(300); // media commits to GitHub can be slow
            $slug = $isEdit ? $editSlug : slugify($title);
            $imgWebPath = $origImage;
            $imgRepoPath = null;
            $imgBin = null;
            $video = $origVideo;
            $vidRepoPath = null;
            $vidBin = null;

            if ($hasVideo) {
                $mime = (string) (new finfo(FILEINFO_MIME_TYPE))->file($_FILES['video']['tmp_name']);
                $vid = processVideo($_FILES['video']['tmp_name'], $mime);
                if (!$vid) {
                    $err = 'The video must be MP4, WebM or MOV.';
                } else {
                    [$vidBin, $vExt] = $vid;
                    $vidRepoPath = "public/videos/{$slug}.{$vExt}";
                    $video = "/videos/{$slug}.{$vExt}";
                }
            } elseif ($videoUrl !== '') {
                $video = $videoUrl;
            }

            if ($err === '' && $hasPhoto) {
                $mime = (string) (new finfo(FILEINFO_MIME_TYPE))->file($_FILES['photo']['tmp_name']);
                $image = processImage($_FILES['photo']['tmp_name'], $mime);
                if (!$image) {
                    $err = 'The photo must be a JPG, PNG or WebP image.';
                } else {
                    [$imgBin, $ext] = $image;
                    $imgRepoPath = "public/images/news/{$slug}.{$ext}";
                    $imgWebPath = "/images/news/{$slug}.{$ext}";
                }
            }

            if ($err === '') {
                $md = "---\n"
                    . 'title: ' . yamlQuote($title) . "\n"
                    . "date: {$date}T00:00:00.000Z\n"
                    . "category: {$category}\n"
                    . "image: {$imgWebPath}\n"
                    . 'imageAlt: ' . yamlQuote($imageAlt) . "\n"
                    . 'description: ' . yamlQuote($description) . "\n"
                    . ($video !== '' ? "video: {$video}\n" : '')
                    . "---\n\n" . $body . "\n";

                if ($imgRepoPath) {
                    [$okImg, $errImg] = ghCommit($config, $imgRepoPath, (string) $imgBin, "news: photo for {$slug}");
                    if (!$okImg) $err = $errImg;
                }
                if ($err === '' && $vidRepoPath) {
                    [$okVid, $errVid] = ghCommit($config, $vidRepoPath, (string) $vidBin, "news: video for {$slug}");
                    if (!$okVid) $err = $errVid;
                }
                if ($err === '') {
                    [$okMd, $errMd] = ghCommit($config, "src/content/news/{$locale}/{$slug}.md", $md, ($isEdit ? 'news: update ' : 'news: ') . $title);
                    if ($okMd) {
                        $base = LOCALE_NEWS_BASE[$locale];
                        $verb = $isEdit ? 'Updated' : 'Published';
                        $msg = "{$verb} \"{$title}\". It will appear at https://hospitalarias.in{$base} in about 3-5 minutes.";
                    } else {
                        $err = $errMd;
                    }
                }
            }
        }
    }
}

// ---------- Manage list ----------
$articles = ($logged && $config) ? ghListNews($config) : [];
$articlesByLocale = [];
if ($articles) {
    $contents = ghGetFiles($config, array_column($articles, 'path'));
    foreach ($articles as &$a) {
        [$f] = parseNewsFile($contents[$a['path']] ?? '');
        $a['title'] = $f['title'] !== '' ? $f['title'] : $a['slug'];
        $a['date'] = $f['date'] !== '' ? $f['date'] : '0000-00-00';
        $a['category'] = $f['category'] !== '' ? $f['category'] : 'General';
    }
    unset($a);
    usort($articles, fn($x, $y) => strcmp($y['date'], $x['date']) ?: strcmp($x['slug'], $y['slug']));
    foreach ($articles as $a) {
        $articlesByLocale[$a['locale']][substr($a['date'], 0, 4)][substr($a['date'], 5, 2)][] = $a;
    }
}
$editKey = $editing ? $editing['locale'] . '/' . $editing['slug'] : '';

// View state + bulk JSON fetch (parallel) for display
$view = (string) ($_GET['view'] ?? 'article');
if (!in_array($view, ['article', 'gallery', 'notice', 'newsletter', 'hero'], true)) $view = 'article';
$jsonData = [];
if ($logged && $config) {
    foreach (ghGetFiles($config, [GALLERY_JSON, NOTICE_JSON, NEWS_JSON, HEROES_JSON]) as $p => $c) {
        $d = json_decode($c, true);
        if (is_array($d)) $jsonData[$p] = $d;
    }
}
$galleryItems = $jsonData[GALLERY_JSON] ?? [];
$noticeData = $jsonData[NOTICE_JSON] ?? ['enabled' => false, 'text' => '', 'href' => ''];
$newsItems = $jsonData[NEWS_JSON] ?? [];
$heroesData = $jsonData[HEROES_JSON] ?? [];

// Visit stats written by track.php (stored outside public_html)
$statsFile = dirname(__DIR__) . '/panel-stats.json';
$stats = is_file($statsFile) ? (json_decode((string) file_get_contents($statsFile), true) ?: []) : [];
$cutoff30 = gmdate('Y-m-d', strtotime('-30 days'));
$todayCount = array_sum($stats[gmdate('Y-m-d')] ?? []);
$monthCount = 0;
$topPages = [];
foreach ($stats as $d => $paths) {
    if ($d >= $cutoff30 && is_array($paths)) {
        $monthCount += array_sum($paths);
        foreach ($paths as $pp => $cc) $topPages[$pp] = ($topPages[$pp] ?? 0) + $cc;
    }
}
arsort($topPages);
$topPages = array_slice($topPages, 0, 4, true);

// Form values: defaults <- article being edited <- what the user just typed
// (so a failed publish never wipes their work).
$form = [
    'locale' => 'en', 'date' => gmdate('Y-m-d'), 'title' => '', 'category' => '',
    'description' => '', 'imageAlt' => '', 'body' => '', 'video_url' => '',
];
if ($editing) {
    $form = array_merge($form, [
        'locale' => $editing['locale'],
        'date' => $editing['fields']['date'],
        'title' => $editing['fields']['title'],
        'category' => $editing['fields']['category'],
        'description' => $editing['fields']['description'],
        'imageAlt' => $editing['fields']['imageAlt'],
        'body' => $editing['body'],
        'video_url' => str_starts_with($editing['fields']['video'], 'http') ? $editing['fields']['video'] : '',
    ]);
}
if ($err !== '' && (($_POST['action'] ?? '') === 'publish')) {
    foreach ([
        'locale' => 'locale', 'date' => 'date', 'title' => 'title',
        'category' => 'category', 'description' => 'description',
        'imageAlt' => 'image_alt', 'body' => 'body', 'video_url' => 'video_url',
    ] as $k => $postKey) {
        $v = trim((string) ($_POST[$postKey] ?? ''));
        if ($v !== '') $form[$k] = $v;
    }
}
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>News Panel — Benedict Menni Centre</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; background: #f4f2ef; color: #26221e; margin: 0; }
  a { color: #7a2e2e; }

  /* ---------- Sidebar layout (logged in) ---------- */
  .layout { display: flex; min-height: 100svh; }
  .side {
    width: 250px; flex-shrink: 0; background: #fff; border-right: 1px solid #e6e0d8;
    padding: 18px 14px; position: sticky; top: 0; height: 100svh; overflow-y: auto;
    display: flex; flex-direction: column; gap: 14px;
  }
  .side-brand { font-size: 1.05rem; font-weight: 800; margin: 0; }
  .side-brand span { display: block; font-size: .72rem; font-weight: 600; color: #6b655c; margin-top: 2px; }
  .btn-new {
    display: block; background: #7a2e2e; color: #fff; text-align: center; text-decoration: none;
    font-weight: 700; font-size: .92rem; padding: 11px; border-radius: 8px;
  }
  .btn-new:hover { background: #612525; }
  .btn-gallery {
    display: block; background: #fff; color: #7a2e2e; border: 1px solid #d8d2c8;
    text-align: center; text-decoration: none; font-weight: 700; font-size: .85rem;
    padding: 9px; border-radius: 8px;
  }
  .btn-gallery:hover { border-color: #7a2e2e; }
  .gal-list { margin-top: 20px; display: flex; flex-direction: column; gap: 6px; }
  .gal-row {
    display: flex; align-items: center; gap: 8px; font-size: .85rem;
    padding: 8px 10px; border: 1px solid #eee8de; border-radius: 8px;
  }
  .gal-row .cap { flex: 1; overflow: hidden; text-overflow: ellipsis; }
  .gal-row .view { color: #6b655c; text-decoration: none; font-size: .78rem; }
  .gal-row .del { border: 0; background: none; color: #b0564f; cursor: pointer; font-size: 1rem; padding: 0 2px; }
  .side-label { font-size: .7rem; font-weight: 800; text-transform: uppercase; letter-spacing: .05em; color: #6b655c; margin: 6px 4px 6px; }
  .side-group { font-size: .72rem; font-weight: 700; color: #6b655c; text-transform: uppercase; letter-spacing: .05em; margin: 10px 4px 4px; }
  .side-item {
    display: flex; align-items: center; gap: 6px; padding: 8px 8px; border-radius: 8px;
    text-decoration: none; color: #26221e; font-size: .85rem; line-height: 1.25;
  }
  .side-item:hover { background: #f4f2ef; }
  .side-item.active { background: #f7ecec; color: #7a2e2e; font-weight: 700; }
  .side-item .slug { flex: 1; overflow: hidden; text-overflow: ellipsis; color: inherit; text-decoration: none; }
  .side-item.active .slug { color: #7a2e2e; }
  .side-item .view { font-size: .78rem; color: #6b655c; text-decoration: none; }
  .side-item .del {
    border: 0; background: none; color: #b0564f; cursor: pointer; font-size: .95rem;
    padding: 0 4px; line-height: 1;
  }
  .side-item .del:hover { color: #922; }
  .side-foot { margin-top: auto; padding-top: 12px; border-top: 1px solid #f0ece5; font-size: .82rem; display: flex; flex-direction: column; gap: 6px; }
  .side-foot a { text-decoration: none; }
  .side-empty { color: #6b655c; font-size: .85rem; margin: 4px; }

  /* Date-grouped article tree */
  .side-filter { width: 100%; padding: 8px 10px; font-size: .85rem; border: 1px solid #d8d2c8; border-radius: 8px; }
  details.year { margin: 0 0 2px; }
  details.year summary {
    cursor: pointer; font-size: .8rem; font-weight: 700; color: #6b655c;
    padding: 5px 6px; border-radius: 6px; list-style: none;
    display: flex; align-items: center; gap: 4px;
  }
  details.year summary::-webkit-details-marker { display: none; }
  details.year summary::before { content: '▸'; font-size: .68rem; }
  details.year[open] summary::before { content: '▾'; }
  details.year summary:hover { background: #f4f2ef; }
  details.year summary .cnt { margin-left: auto; font-weight: 600; font-size: .72rem; color: #9a938a; }
  .month-head { font-size: .7rem; font-weight: 700; color: #9a938a; margin: 5px 14px 0; }
  .side-item .cat { display: block; font-size: .66rem; color: #9a938a; font-weight: 400; }

  /* Visit stats card */
  .side-stats { background: #f9f7f4; border: 1px solid #eee8de; border-radius: 10px; padding: 10px 12px; }
  .side-stats .side-label { margin: 0 0 4px; }
  .stat-row { display: flex; justify-content: space-between; gap: 8px; font-size: .8rem; padding: 2px 0; }
  .stat-row span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .stat-row b { font-variant-numeric: tabular-nums; }
  .stat-row.top { color: #6b655c; font-size: .72rem; }
  .stats-link { font-size: .74rem; text-decoration: none; display: inline-block; margin-top: 6px; }

  .main { flex: 1; padding: 26px 20px 40px; display: flex; justify-content: center; align-items: flex-start; }
  .main .card { width: 100%; max-width: 620px; }

  /* ---------- Card / form ---------- */
  .card { background: #fff; border-radius: 14px; padding: 28px; box-shadow: 0 6px 24px rgba(0,0,0,.08); }
  .centered { min-height: 100svh; display: flex; align-items: center; justify-content: center; padding: 24px; }
  .centered .card { width: 100%; max-width: 420px; }
  h1 { font-size: 1.35rem; margin: 0 0 4px; }
  .sub { color: #6b655c; font-size: .9rem; margin: 0 0 20px; }
  label { display: block; font-weight: 600; font-size: .85rem; margin: 16px 0 4px; }
  input, select, textarea { width: 100%; padding: 11px 12px; border: 1px solid #d8d2c8; border-radius: 8px; font: inherit; font-size: 1rem; background: #fff; }
  input[type=checkbox] { width: auto; }
  label.check { display: flex; align-items: center; gap: 8px; }
  .hero-form { padding: 4px 0 14px; border-bottom: 1px solid #f0ece5; }
  input[readonly] { background: #f4f2ef; }
  textarea { min-height: 160px; resize: vertical; }
  .hint { font-size: .78rem; color: #6b655c; margin-top: 3px; }
  .card button[type=submit] { margin-top: 22px; width: 100%; padding: 13px; border: 0; border-radius: 8px; background: #7a2e2e; color: #fff; font-size: 1rem; font-weight: 700; cursor: pointer; }
  .card button[type=submit]:hover { background: #612525; }
  .ok { background: #e8f5e9; border: 1px solid #a5d6a7; color: #1b5e20; padding: 12px 14px; border-radius: 8px; margin-bottom: 16px; }
  .err { background: #fdecea; border: 1px solid #f5b7b1; color: #922; padding: 12px 14px; border-radius: 8px; margin-bottom: 16px; }
  .row { display: flex; gap: 12px; } .row > div { flex: 1; }
  .links { display: flex; justify-content: space-between; margin-top: 18px; font-size: .85rem; }
  form.inline { display: inline; margin: 0; }

  @media (max-width: 860px) {
    .layout { flex-direction: column; }
    .side {
      width: 100%; position: static; height: auto; max-height: none;
      border-right: 0; border-bottom: 1px solid #e6e0d8;
    }
    .side nav { max-height: 42svh; overflow-y: auto; }
    .main { padding: 18px 12px 32px; }
    .card { padding: 20px; }
  }
</style>
</head>
<body>

<?php if (!$logged): ?>
<div class="centered">
  <div class="card">
    <h1>News Panel</h1>
    <p class="sub">Benedict Menni Psychosocial Rehabilitation Centre</p>
    <?php if ($err): ?><div class="err"><?= e($err) ?></div><?php endif; ?>
    <form method="post">
      <input type="hidden" name="action" value="login">
      <label for="password">Password</label>
      <input type="password" id="password" name="password" required autofocus autocomplete="current-password">
      <button type="submit">Sign in</button>
    </form>
  </div>
</div>

<?php else: ?>
<div class="layout">
  <aside class="side">
    <p class="side-brand">News Panel<span>Benedict Menni Centre</span></p>
    <a class="btn-new" href="panel.php">+ New article</a>
    <a class="btn-gallery" href="?view=gallery">Photos — gallery (<?= count($galleryItems) ?>)</a>
    <a class="btn-gallery" href="?view=notice">Announcement<?= !empty($noticeData['enabled']) ? ' · ON' : '' ?></a>
    <a class="btn-gallery" href="?view=newsletter">Newsletters (<?= count($newsItems) ?>)</a>
    <a class="btn-gallery" href="?view=hero">Page photos</a>

    <div class="side-stats" aria-label="Visit statistics">
      <p class="side-label">Visits</p>
      <div class="stat-row"><span>Today</span><b><?= $todayCount ?></b></div>
      <div class="stat-row"><span>Last 30 days</span><b><?= $monthCount ?></b></div>
      <?php foreach ($topPages as $pp => $cc): ?>
        <div class="stat-row top"><span title="<?= e($pp) ?>"><?= e($pp) ?></span><b><?= $cc ?></b></div>
      <?php endforeach; ?>
      <a class="stats-link" href="https://analytics.google.com/" target="_blank" rel="noopener">Full stats (Google) ↗</a>
    </div>

    <nav aria-label="Existing articles">
      <p class="side-label">Articles</p>
      <input id="af" class="side-filter" type="search" placeholder="Filter by title or category…" aria-label="Filter articles">
      <?php if ($articlesByLocale): ?>
        <?php foreach ($articlesByLocale as $loc => $years): ?>
          <div class="locale-group">
            <p class="side-group"><?= e(strtoupper($loc)) ?> — <?= e(LOCALES[$loc] ?? $loc) ?></p>
            <?php $firstYear = true; foreach ($years as $year => $months): ?>
              <details class="year" <?= $firstYear ? 'open' : '' ?>>
                <summary><?= (string) $year === '0000' ? 'Undated' : e((string) $year) ?><span class="cnt"><?= array_sum(array_map('count', $months)) ?></span></summary>
                <?php foreach ($months as $mon => $items): ?>
                  <div class="month-group">
                    <p class="month-head"><?= e(MONTHS[$mon] ?? 'Undated') ?></p>
                    <?php foreach ($items as $a):
                      $key = $a['locale'] . '/' . $a['slug']; ?>
                      <div class="side-item<?= $key === $editKey ? ' active' : '' ?>">
                        <a class="slug" href="?edit=<?= e($key) ?>" title="<?= e($a['slug']) ?>">
                          <?= e($a['title']) ?><span class="cat"><?= e($a['category']) ?></span>
                        </a>
                        <a class="view" href="https://hospitalarias.in<?= e(LOCALE_NEWS_BASE[$a['locale']]) . e($a['slug']) ?>/" target="_blank" rel="noopener" title="View on site">↗</a>
                        <form class="inline" method="post" onsubmit="return confirm('Delete &quot;<?= e($a['slug']) ?>&quot; (<?= e($a['locale']) ?>)? This cannot be undone.');">
                          <input type="hidden" name="action" value="delete">
                          <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">
                          <input type="hidden" name="path" value="<?= e($a['path']) ?>">
                          <button type="submit" class="del" title="Delete">×</button>
                        </form>
                      </div>
                    <?php endforeach; ?>
                  </div>
                <?php endforeach; ?>
              </details>
            <?php $firstYear = false; endforeach; ?>
          </div>
        <?php endforeach; ?>
      <?php else: ?>
        <p class="side-empty">No articles yet — publish the first one.</p>
      <?php endif; ?>
    </nav>

    <div class="side-foot">
      <a href="https://hospitalarias.in/en/news/" target="_blank" rel="noopener">View news page ↗</a>
      <a href="?logout=1">Sign out</a>
    </div>
  </aside>

  <main class="main">
    <?php if ($view === 'gallery'): ?>
    <div class="card">
      <h1>Gallery photos</h1>
      <p class="sub">Add photos of activities — they appear on the public gallery page.</p>

      <?php if ($msg): ?><div class="ok"><?= e($msg) ?></div><?php endif; ?>
      <?php if ($err): ?><div class="err"><?= e($err) ?></div><?php endif; ?>

      <form method="post" enctype="multipart/form-data">
        <input type="hidden" name="action" value="gallery_add">
        <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">

        <label for="gphoto">Photo</label>
        <input type="file" id="gphoto" name="photo" accept="image/jpeg,image/png,image/webp" required>
        <p class="hint">JPG, PNG or WebP, up to 12 MB. Large photos are resized automatically.</p>

        <label for="caption">Caption</label>
        <input type="text" id="caption" name="caption" required maxlength="120" placeholder="e.g. Residents gardening in the morning">
        <p class="hint">One short sentence — shown under the photo.</p>

        <button type="submit">Add to gallery</button>
      </form>

      <?php if ($galleryItems): ?>
      <div class="gal-list">
        <?php foreach ($galleryItems as $g): ?>
          <div class="gal-row">
            <span class="cap" title="<?= e($g['src'] ?? '') ?>"><?= e($g['alt'] ?? '') ?></span>
            <a class="view" href="https://hospitalarias.in<?= e($g['src'] ?? '') ?>" target="_blank" rel="noopener" title="Open photo">↗</a>
            <form class="inline" method="post" onsubmit="return confirm('Remove &quot;<?= e($g['alt'] ?? '') ?>&quot; from the gallery? The photo file is deleted too.');">
              <input type="hidden" name="action" value="gallery_delete">
              <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">
              <input type="hidden" name="src" value="<?= e($g['src'] ?? '') ?>">
              <button type="submit" class="del" title="Remove">×</button>
            </form>
          </div>
        <?php endforeach; ?>
      </div>
      <?php else: ?>
        <p class="hint" style="margin-top:16px">No photos added yet — the public gallery still shows the original photos.</p>
      <?php endif; ?>

      <div class="links">
        <a href="panel.php">+ New article</a>
        <a href="https://hospitalarias.in/en/gallery/" target="_blank" rel="noopener">View gallery ↗</a>
        <a href="?logout=1">Sign out</a>
      </div>
    </div>
    <?php elseif ($view === 'notice'): ?>
    <div class="card">
      <h1>Announcement bar</h1>
      <p class="sub">Shows a coloured banner at the top of every page — for campaigns or urgent news.</p>

      <?php if ($msg): ?><div class="ok"><?= e($msg) ?></div><?php endif; ?>
      <?php if ($err): ?><div class="err"><?= e($err) ?></div><?php endif; ?>

      <form method="post">
        <input type="hidden" name="action" value="notice_save">
        <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">

        <label class="check"><input type="checkbox" name="enabled" value="1" <?= !empty($noticeData['enabled']) ? 'checked' : '' ?>> Show the announcement on the website</label>

        <label for="notice-text">Text</label>
        <input type="text" id="notice-text" name="text" maxlength="160" value="<?= e((string) ($noticeData['text'] ?? '')) ?>" placeholder="e.g. Christmas donation campaign — help us reach the goal">

        <label for="notice-href">Link (optional)</label>
        <input type="text" id="notice-href" name="href" value="<?= e((string) ($noticeData['href'] ?? '')) ?>" placeholder="/en/get-involved/donate/ or https://…">
        <p class="hint">Where the banner takes you when clicked — a page on this site or a full link.</p>

        <button type="submit">Save announcement</button>
      </form>

      <div class="links">
        <a href="panel.php">+ New article</a>
        <a href="https://hospitalarias.in/" target="_blank" rel="noopener">View site ↗</a>
        <a href="?logout=1">Sign out</a>
      </div>
    </div>
    <?php elseif ($view === 'newsletter'): ?>
    <div class="card">
      <h1>Newsletters</h1>
      <p class="sub">Upload PDF bulletins — they appear listed on the newsletter page.</p>

      <?php if ($msg): ?><div class="ok"><?= e($msg) ?></div><?php endif; ?>
      <?php if ($err): ?><div class="err"><?= e($err) ?></div><?php endif; ?>

      <form method="post" enctype="multipart/form-data">
        <input type="hidden" name="action" value="newsletter_add">
        <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">

        <label for="pdf">PDF file</label>
        <input type="file" id="pdf" name="pdf" accept="application/pdf" required>
        <p class="hint">PDF only, up to 20 MB.</p>

        <div class="row">
          <div>
            <label for="ntitle">Title</label>
            <input type="text" id="ntitle" name="title" required maxlength="120" placeholder="e.g. Newsletter — January 2027">
          </div>
          <div>
            <label for="ndate">Date</label>
            <input type="date" id="ndate" name="date" value="<?= gmdate('Y-m-d') ?>">
          </div>
        </div>

        <button type="submit">Add newsletter</button>
      </form>

      <?php if ($newsItems): ?>
      <div class="gal-list">
        <?php foreach ($newsItems as $n): ?>
          <div class="gal-row">
            <span class="cap" title="<?= e($n['file'] ?? '') ?>"><?= e($n['title'] ?? '') ?><?= !empty($n['date']) ? ' · ' . e((string) $n['date']) : '' ?></span>
            <a class="view" href="https://hospitalarias.in<?= e($n['file'] ?? '') ?>" target="_blank" rel="noopener" title="Open PDF">↗</a>
            <form class="inline" method="post" onsubmit="return confirm('Remove &quot;<?= e($n['title'] ?? '') ?>&quot;? The PDF file is deleted too.');">
              <input type="hidden" name="action" value="newsletter_delete">
              <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">
              <input type="hidden" name="file" value="<?= e($n['file'] ?? '') ?>">
              <button type="submit" class="del" title="Remove">×</button>
            </form>
          </div>
        <?php endforeach; ?>
      </div>
      <?php else: ?>
        <p class="hint" style="margin-top:16px">No newsletters uploaded yet.</p>
      <?php endif; ?>

      <div class="links">
        <a href="panel.php">+ New article</a>
        <a href="https://hospitalarias.in/en/newsletter/" target="_blank" rel="noopener">View newsletter page ↗</a>
        <a href="?logout=1">Sign out</a>
      </div>
    </div>
    <?php elseif ($view === 'hero'): ?>
    <div class="card">
      <h1>Page photos</h1>
      <p class="sub">Swap the main photo of a page — upload a new one, or reset to the original.</p>

      <?php if ($msg): ?><div class="ok"><?= e($msg) ?></div><?php endif; ?>
      <?php if ($err): ?><div class="err"><?= e($err) ?></div><?php endif; ?>

      <?php foreach (HERO_SLOTS as $slot => $label):
        $cur = $heroesData[$slot] ?? ''; ?>
        <div class="gal-row" style="align-items:flex-start">
          <div class="cap">
            <b><?= e($label) ?></b><br>
            <span class="hint"><?= $cur !== '' ? 'Custom: ' . e($cur) : 'Using the original photo' ?></span>
          </div>
        </div>
        <form method="post" enctype="multipart/form-data" class="hero-form">
          <input type="hidden" name="action" value="hero_save">
          <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">
          <input type="hidden" name="slot" value="<?= e($slot) ?>">
          <input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required>
          <div style="display:flex;gap:8px;margin-top:8px">
            <button type="submit" style="flex:1">Change photo</button>
            <?php if ($cur !== ''): ?>
              <button type="submit" formnovalidate name="action" value="hero_reset" style="flex:1;background:#fff;color:#7a2e2e;border:1px solid #d8d2c8">Reset to original</button>
            <?php endif; ?>
          </div>
        </form>
      <?php endforeach; ?>

      <div class="links">
        <a href="panel.php">+ New article</a>
        <a href="https://hospitalarias.in/" target="_blank" rel="noopener">View site ↗</a>
        <a href="?logout=1">Sign out</a>
      </div>
    </div>
    <?php else: ?>
    <div class="card">
      <h1><?= $editing ? 'Edit article' : 'New article' ?></h1>
      <p class="sub"><?= $editing
        ? 'Editing ' . e($editing['slug']) . '.md — the URL stays the same.'
        : 'Publish directly to the website (~3-5 min to appear).' ?></p>

      <?php if ($msg): ?><div class="ok"><?= e($msg) ?></div><?php endif; ?>
      <?php if ($err): ?><div class="err"><?= e($err) ?></div><?php endif; ?>

      <form method="post" enctype="multipart/form-data">
        <input type="hidden" name="action" value="publish">
        <input type="hidden" name="csrf" value="<?= e((string) ($_SESSION['csrf'] ?? '')) ?>">
        <?php if ($editing): ?>
          <input type="hidden" name="edit_slug" value="<?= e($editing['slug']) ?>">
          <input type="hidden" name="edit_locale" value="<?= e($editing['locale']) ?>">
          <input type="hidden" name="orig_image" value="<?= e($editing['fields']['image']) ?>">
          <input type="hidden" name="orig_video" value="<?= e($editing['fields']['video']) ?>">
        <?php endif; ?>

        <div class="row">
          <div>
            <label for="locale">Article language</label>
            <?php if ($editing): ?>
              <input type="text" value="<?= e(LOCALES[$editing['locale']]) ?>" readonly>
            <?php else: ?>
              <select id="locale" name="locale">
                <?php foreach (LOCALES as $code => $label): ?>
                  <option value="<?= e($code) ?>" <?= $code === $form['locale'] ? 'selected' : '' ?>><?= e($label) ?></option>
                <?php endforeach; ?>
              </select>
            <?php endif; ?>
          </div>
          <div>
            <label for="date">Date</label>
            <input type="date" id="date" name="date" value="<?= e($form['date']) ?>">
          </div>
        </div>

        <label for="title">Title</label>
        <input type="text" id="title" name="title" required maxlength="140" value="<?= e($form['title']) ?>">

        <label for="category">Category</label>
        <select id="category" name="category">
          <?php
          $cats = CATEGORIES;
          $cur = $form['category'];
          if ($cur !== '' && !in_array($cur, $cats, true)) array_unshift($cats, $cur);
          foreach ($cats as $c): ?>
            <option <?= $c === $cur ? 'selected' : '' ?>><?= e($c) ?></option>
          <?php endforeach; ?>
        </select>

        <label for="description">Short description</label>
        <input type="text" id="description" name="description" required maxlength="200" value="<?= e($form['description']) ?>">
        <p class="hint">One or two sentences — shown on the news card.</p>

        <label for="photo">Photo</label>
        <input type="file" id="photo" name="photo" accept="image/jpeg,image/png,image/webp" <?= $editing ? '' : 'required' ?>>
        <p class="hint"><?= $editing ? 'Leave empty to keep the current photo.' : 'JPG, PNG or WebP, up to 12 MB. Large photos are resized automatically.' ?></p>
        <?php if ($editing && $editing['fields']['image'] !== ''): ?>
          <p class="hint">Current: <a href="https://hospitalarias.in<?= e($editing['fields']['image']) ?>" target="_blank" rel="noopener"><?= e($editing['fields']['image']) ?></a></p>
        <?php endif; ?>

        <label for="video_url">Video — YouTube, Vimeo or Instagram link (optional)</label>
        <input type="url" id="video_url" name="video_url" placeholder="https://youtube.com/watch?v=… or https://instagram.com/reel/…" value="<?= e($form['video_url']) ?>">
        <p class="hint">Paste a YouTube/Vimeo link, or an Instagram post/reel link to show it inside the article.</p>

        <label for="video">Or upload a video file</label>
        <input type="file" id="video" name="video" accept="video/mp4,video/webm,video/quicktime">
        <p class="hint">MP4 or WebM, max 45 MB. <?= $editing ? 'Leave empty to keep the current video.' : 'For longer videos use YouTube — faster and takes no space.' ?></p>
        <?php if ($editing && $editing['fields']['video'] !== ''): ?>
          <p class="hint">Current: <?= e($editing['fields']['video']) ?></p>
        <?php endif; ?>

        <label for="image_alt">Photo description</label>
        <input type="text" id="image_alt" name="image_alt" required maxlength="160" value="<?= e($form['imageAlt']) ?>">
        <p class="hint">Describe the photo for blind readers, e.g. "Residents at the garden workshop".</p>

        <label for="body">Article text</label>
        <textarea id="body" name="body" required><?= e($form['body']) ?></textarea>
        <p class="hint">Plain text. Leave an empty line between paragraphs.</p>

        <button type="submit"><?= $editing ? 'Update article' : 'Publish' ?></button>
      </form>
      <div class="links">
        <?php if ($editing): ?><a href="panel.php">+ New article</a><?php endif; ?>
        <a href="https://hospitalarias.in/en/news/" target="_blank" rel="noopener">View news page ↗</a>
        <a href="?logout=1">Sign out</a>
      </div>
    </div>
    <?php endif; ?>
  </main>
</div>
<?php endif; ?>

<script>
  const af = document.getElementById('af');
  if (af) af.addEventListener('input', () => {
    const q = af.value.trim().toLowerCase();
    document.querySelectorAll('.side-item').forEach(el => {
      el.style.display = !q || el.textContent.toLowerCase().includes(q) ? '' : 'none';
    });
    document.querySelectorAll('details.year').forEach(d => {
      if (q && !d.open) { d.open = true; d.dataset.auto = '1'; }
      else if (!q && d.dataset.auto) { d.open = false; delete d.dataset.auto; }
    });
    document.querySelectorAll('.month-group, .locale-group').forEach(g => {
      const anyVisible = [...g.querySelectorAll('.side-item')].some(i => i.style.display !== 'none');
      g.style.display = q && !anyVisible ? 'none' : '';
    });
  });
</script>

</body>
</html>
